import type { Daypart, Island, Listing, Pepper } from "./types";

export type CatalogPot = {
  id: string;
  cookId: string;
  cookName: string;
  cookLine: string;
  neighborhood: string;
  island: Island;
  title: string;
  description: string;
  priceCents: number;
  servingsLeft: number;
  tags: string[];
  pepper: Pepper;
  daypart: Daypart;
  visual: string;
  pickupWindow: string;
  /** 0 Sun … 6 Sat. Empty = any day. */
  days: number[];
};

export const CATALOG: CatalogPot[] = [
  {
    id: "seed_doubles",
    cookId: "seed_kamla",
    cookName: "Kamla Persad",
    cookLine: "St. James, wrapping since savannah days",
    neighborhood: "St. James",
    island: "trinidad",
    title: "Doubles (bara, channa, slight spicy)",
    description:
      "Soft bara, stewed channa, cucumber, and tamarind. Slight or slight-plus — say in the note.",
    priceCents: 1200,
    servingsLeft: 20,
    tags: ["breakfast", "lunch", "vegetarian"],
    pepper: "slight",
    daypart: "morning",
    visual: "doubles",
    pickupWindow: "6:30–10:00am",
    days: [1, 2, 3, 4, 5, 6],
  },
  {
    id: "seed_choka",
    cookId: "seed_priya_tt",
    cookName: "Priya Ramcharan",
    cookLine: "San Juan, fire-roast first",
    neighborhood: "San Juan",
    island: "trinidad",
    title: "Sada roti + tomato choka",
    description:
      "Hot sada, fire-roasted tomato choka, and a side of baigan if you ask.",
    priceCents: 1800,
    servingsLeft: 10,
    tags: ["breakfast", "vegetarian"],
    pepper: "slight",
    daypart: "morning",
    visual: "choka",
    pickupWindow: "6:00–9:00am",
    days: [0, 1, 2, 3],
  },
  {
    id: "seed_saltfish",
    cookId: "seed_helen",
    cookName: "Helen Gopaul",
    cookLine: "Diego Martin morning bake",
    neighborhood: "Diego Martin",
    island: "trinidad",
    title: "Bake and saltfish",
    description:
      "Coconut bake, stewed saltfish, tomato, and onion. Breakfast wrap for the road.",
    priceCents: 2800,
    servingsLeft: 8,
    tags: ["breakfast"],
    pepper: "slight",
    daypart: "morning",
    visual: "bake",
    pickupWindow: "6:30–9:30am",
    days: [1, 2, 4],
  },
  {
    id: "seed_buljol",
    cookId: "seed_priya_tt",
    cookName: "Priya Ramcharan",
    cookLine: "San Juan, coconut bake on the side",
    neighborhood: "San Juan",
    island: "trinidad",
    title: "Buljol + coconut bake",
    description:
      "Saltfish buljol with tomato, onion, and cucumber. One bake per plate.",
    priceCents: 2500,
    servingsLeft: 8,
    tags: ["breakfast"],
    pepper: "slight",
    daypart: "morning",
    visual: "choka",
    pickupWindow: "7:00–10:00am",
    days: [3, 5],
  },
  {
    id: "seed_roti",
    cookId: "seed_asha",
    cookName: "Asha Mohammed",
    cookLine: "San Fernando roti, no shortcuts",
    neighborhood: "San Fernando",
    island: "trinidad",
    title: "Dhalpuri + chicken roti",
    description:
      "Dhalpuri skin, curry chicken, potato, and channa. Ask for buss-up-shut in the note.",
    priceCents: 4000,
    servingsLeft: 10,
    tags: ["lunch", "dinner"],
    pepper: "slight",
    daypart: "lunch",
    visual: "roti",
    pickupWindow: "11:00am–2:00pm",
    days: [0, 2, 4, 6],
  },
  {
    id: "seed_goat_roti",
    cookId: "seed_asha",
    cookName: "Asha Mohammed",
    cookLine: "South-side goat, weekend pot",
    neighborhood: "San Fernando",
    island: "trinidad",
    title: "Goat roti",
    description: "Curry goat, potato, and dhalpuri. Bones in unless you say otherwise.",
    priceCents: 5000,
    servingsLeft: 8,
    tags: ["lunch", "dinner"],
    pepper: "slight-plus",
    daypart: "lunch",
    visual: "roti",
    pickupWindow: "11:30am–2:30pm",
    days: [0, 6],
  },
  {
    id: "seed_bussup",
    cookId: "seed_ravi",
    cookName: "Ravi Singh",
    cookLine: "Tunapuna buss-up and channa",
    neighborhood: "Tunapuna",
    island: "trinidad",
    title: "Buss-up-shut + curry channa",
    description: "Torn paratha, curry channa and aloo, mango talkari on the side.",
    priceCents: 3500,
    servingsLeft: 10,
    tags: ["lunch", "vegetarian"],
    pepper: "slight",
    daypart: "lunch",
    visual: "roti",
    pickupWindow: "11:00am–2:00pm",
    days: [1, 3],
  },
  {
    id: "seed_pelau",
    cookId: "seed_marlon",
    cookName: "Marlon Baptiste",
    cookLine: "Central pot, browned sugar first",
    neighborhood: "Chaguanas",
    island: "trinidad",
    title: "Chicken pelau plate",
    description:
      "Browned-sugar pelau with pigeon peas, pumpkin, and coleslaw. Packed in a foil tray.",
    priceCents: 4500,
    servingsLeft: 12,
    tags: ["lunch", "dinner"],
    pepper: "slight",
    daypart: "lunch",
    visual: "pelau",
    pickupWindow: "12:00–6:00pm",
    days: [1, 2, 3, 5],
  },
  {
    id: "seed_veg_pelau",
    cookId: "seed_marlon",
    cookName: "Marlon Baptiste",
    cookLine: "Same pot, no meat",
    neighborhood: "Chaguanas",
    island: "trinidad",
    title: "Vegetable pelau",
    description: "Pigeon peas, pumpkin, carrot, and coconut. Vegetarian foil tray.",
    priceCents: 3800,
    servingsLeft: 8,
    tags: ["lunch", "vegetarian"],
    pepper: "slight",
    daypart: "lunch",
    visual: "pelau",
    pickupWindow: "12:00–5:00pm",
    days: [4],
  },
  {
    id: "seed_sunday_lunch",
    cookId: "seed_indra",
    cookName: "Indra Rampersad",
    cookLine: "Campus-side Sunday plate",
    neighborhood: "St. Augustine",
    island: "trinidad",
    title: "Sunday lunch: stew chicken, macaroni pie, callaloo",
    description:
      "Stew chicken, baked macaroni pie, callaloo, and a spoon of rice.",
    priceCents: 5500,
    servingsLeft: 9,
    tags: ["lunch", "dinner"],
    pepper: "slight",
    daypart: "lunch",
    visual: "sunday",
    pickupWindow: "12:00–3:00pm",
    days: [0],
  },
  {
    id: "seed_curry_duck",
    cookId: "seed_nadia",
    cookName: "Nadia Ali",
    cookLine: "Arima weekend pot, bone-in",
    neighborhood: "Arima",
    island: "trinidad",
    title: "Curry duck + sada roti",
    description: "Weekend curry duck, potato, and hot sada.",
    priceCents: 7000,
    servingsLeft: 8,
    tags: ["dinner", "spicy"],
    pepper: "plenty",
    daypart: "dinner",
    visual: "duck",
    pickupWindow: "5:00–8:00pm",
    days: [0, 6],
  },
  {
    id: "seed_geera",
    cookId: "seed_nadia",
    cookName: "Nadia Ali",
    cookLine: "Arima geera, lime on the side",
    neighborhood: "Arima",
    island: "trinidad",
    title: "Geera pork",
    description: "Toasted geera pork, pepper, and lime. Cutters box, not a full plate.",
    priceCents: 4500,
    servingsLeft: 10,
    tags: ["dinner", "spicy", "snack"],
    pepper: "plenty",
    daypart: "dinner",
    visual: "duck",
    pickupWindow: "5:00–9:00pm",
    days: [2, 5],
  },
  {
    id: "seed_bake_shark",
    cookId: "seed_dexter",
    cookName: "Dexter Joseph",
    cookLine: "North coast Saturday, still sandy",
    neighborhood: "Maracas",
    island: "trinidad",
    title: "Bake and shark",
    description:
      "Fried bake, seasoned shark, chadon beni, pineapple chow, and pepper sauce.",
    priceCents: 6500,
    servingsLeft: 8,
    tags: ["lunch", "spicy"],
    pepper: "slight-plus",
    daypart: "lunch",
    visual: "bake",
    pickupWindow: "11:00am–3:00pm",
    days: [6],
  },
  {
    id: "seed_kingfish",
    cookId: "seed_dexter",
    cookName: "Dexter Joseph",
    cookLine: "Maracas stew, provision in the box",
    neighborhood: "Maracas",
    island: "trinidad",
    title: "Stew kingfish + provision",
    description: "Stew kingfish, dasheen, and plantain. North-coast Friday plate.",
    priceCents: 7000,
    servingsLeft: 6,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "bake",
    pickupWindow: "4:30–7:00pm",
    days: [5],
  },
  {
    id: "seed_mango_chow",
    cookId: "seed_dexter",
    cookName: "Dexter Joseph",
    cookLine: "Green mango, plenty pepper",
    neighborhood: "Maracas",
    island: "trinidad",
    title: "Mango chow",
    description: "Green mango, chadon beni, salt, and plenty pepper. Saturday bag.",
    priceCents: 1500,
    servingsLeft: 12,
    tags: ["snack", "spicy", "vegetarian"],
    pepper: "plenty",
    daypart: "snack",
    visual: "aloo",
    pickupWindow: "11:00am–4:00pm",
    days: [6],
  },
  {
    id: "seed_crab_dumpling",
    cookId: "seed_yvonne",
    cookName: "Yvonne Clarke",
    cookLine: "Scarborough, coconut and crab",
    neighborhood: "Scarborough",
    island: "tobago",
    title: "Crab and dumpling",
    description: "Tobago curry crab, coconut dumpling, and provision.",
    priceCents: 8500,
    servingsLeft: 6,
    tags: ["dinner"],
    pepper: "slight-plus",
    daypart: "dinner",
    visual: "crab",
    pickupWindow: "4:00–7:00pm",
    days: [0, 5, 6],
  },
  {
    id: "seed_oildown",
    cookId: "seed_curtis",
    cookName: "Curtis Williams",
    cookLine: "Crown Point one-pot",
    neighborhood: "Crown Point",
    island: "tobago",
    title: "Oil down",
    description: "Breadfruit, dasheen bush, coconut milk, and salted meat.",
    priceCents: 5500,
    servingsLeft: 7,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "oil",
    pickupWindow: "5:30–7:30pm",
    days: [0, 3, 6],
  },
  {
    id: "seed_stew_fish_tobago",
    cookId: "seed_yvonne",
    cookName: "Yvonne Clarke",
    cookLine: "Scarborough stew fish",
    neighborhood: "Scarborough",
    island: "tobago",
    title: "Stew fish + coconut dumpling",
    description: "Brown stew fish, dumpling, and provision. Midweek Tobago plate.",
    priceCents: 6500,
    servingsLeft: 6,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "crab",
    pickupWindow: "4:30–7:00pm",
    days: [1, 2, 4],
  },
  {
    id: "seed_drops",
    cookId: "seed_curtis",
    cookName: "Curtis Williams",
    cookLine: "Crown Point sweetie",
    neighborhood: "Crown Point",
    island: "tobago",
    title: "Coconut drops",
    description: "Toasted coconut drops, ginger. Bag of six for tea.",
    priceCents: 2000,
    servingsLeft: 10,
    tags: ["snack", "baked"],
    pepper: "none",
    daypart: "snack",
    visual: "bread",
    pickupWindow: "10:00am–2:00pm",
    days: [2, 4],
  },
  {
    id: "seed_aloo_pholourie",
    cookId: "seed_ravi",
    cookName: "Ravi Singh",
    cookLine: "East–West Corridor snack run",
    neighborhood: "Tunapuna",
    island: "trinidad",
    title: "Aloo pie + pholourie box",
    description: "Two aloo pies and a bag of pholourie with mango and tamarind chutney.",
    priceCents: 2000,
    servingsLeft: 15,
    tags: ["snack", "vegetarian", "baked"],
    pepper: "slight",
    daypart: "snack",
    visual: "aloo",
    pickupWindow: "3:00–6:30pm",
    days: [1, 2, 4],
  },
  {
    id: "seed_saheena",
    cookId: "seed_kamla",
    cookName: "Kamla Persad",
    cookLine: "St. James cutters",
    neighborhood: "St. James",
    island: "trinidad",
    title: "Saheena",
    description: "Dasheen-bush saheena, fried, chutney on the side. Six pieces.",
    priceCents: 1800,
    servingsLeft: 12,
    tags: ["snack", "vegetarian"],
    pepper: "slight",
    daypart: "snack",
    visual: "aloo",
    pickupWindow: "3:00–7:00pm",
    days: [3, 5],
  },
  {
    id: "seed_sweetbread",
    cookId: "seed_helen",
    cookName: "Helen Gopaul",
    cookLine: "Diego Martin bake for tea",
    neighborhood: "Diego Martin",
    island: "trinidad",
    title: "Coconut sweet bread",
    description: "Same-day coconut sweet bread loaf, cherries and raisins.",
    priceCents: 3500,
    servingsLeft: 6,
    tags: ["baked", "snack"],
    pepper: "none",
    daypart: "snack",
    visual: "bread",
    pickupWindow: "9:00am–1:00pm",
    days: [0, 3],
  },
  {
    id: "seed_pone",
    cookId: "seed_indra",
    cookName: "Indra Rampersad",
    cookLine: "St. Augustine cassava pone",
    neighborhood: "St. Augustine",
    island: "trinidad",
    title: "Cassava pone",
    description: "Baked cassava pone squares, coconut and spice. Four pieces.",
    priceCents: 2200,
    servingsLeft: 8,
    tags: ["baked", "snack", "vegetarian"],
    pepper: "none",
    daypart: "snack",
    visual: "bread",
    pickupWindow: "10:00am–2:00pm",
    days: [2, 4],
  },
  {
    id: "seed_corn_soup",
    cookId: "seed_lisa",
    cookName: "Lisa Charles",
    cookLine: "Woodbrook after-fete cup",
    neighborhood: "Woodbrook",
    island: "trinidad",
    title: "Corn soup (fete size)",
    description: "Split peas, sweet corn, dumpling, and provision. Pepper on the side.",
    priceCents: 2500,
    servingsLeft: 14,
    tags: ["snack", "dinner"],
    pepper: "slight-plus",
    daypart: "night",
    visual: "soup",
    pickupWindow: "7:00–11:00pm",
    days: [5, 6],
  },
  {
    id: "seed_fried_rice",
    cookId: "seed_lisa",
    cookName: "Lisa Charles",
    cookLine: "Woodbrook Friday Chinese",
    neighborhood: "Woodbrook",
    island: "trinidad",
    title: "Chicken fried rice box",
    description: "Trini-Chinese fried rice, chicken, and a spring roll. Friday night box.",
    priceCents: 5000,
    servingsLeft: 10,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "sunday",
    pickupWindow: "5:00–9:00pm",
    days: [5],
  },
  {
    id: "seed_chowmein",
    cookId: "seed_lisa",
    cookName: "Lisa Charles",
    cookLine: "Woodbrook chow mein",
    neighborhood: "Woodbrook",
    island: "trinidad",
    title: "Chicken chow mein",
    description: "Soft chow mein, chicken, and veg. Same Friday run as the fried rice.",
    priceCents: 4800,
    servingsLeft: 8,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "sunday",
    pickupWindow: "5:00–9:00pm",
    days: [5],
  },
  {
    id: "seed_souse",
    cookId: "seed_kamla",
    cookName: "Kamla Persad",
    cookLine: "St. James Saturday souse",
    neighborhood: "St. James",
    island: "trinidad",
    title: "Souse",
    description: "Lime, cucumber, pepper. Pig foot souse, cold, for Saturday lime.",
    priceCents: 4000,
    servingsLeft: 8,
    tags: ["snack", "spicy"],
    pepper: "plenty",
    daypart: "snack",
    visual: "soup",
    pickupWindow: "12:00–5:00pm",
    days: [6],
  },
  {
    id: "seed_callaloo_soup",
    cookId: "seed_indra",
    cookName: "Indra Rampersad",
    cookLine: "Dasheen bush, crab optional",
    neighborhood: "St. Augustine",
    island: "trinidad",
    title: "Callaloo soup",
    description: "Dasheen bush, coconut, ochro. Crab if the pot have. Pint container.",
    priceCents: 3000,
    servingsLeft: 10,
    tags: ["dinner"],
    pepper: "slight",
    daypart: "dinner",
    visual: "oil",
    pickupWindow: "5:00–8:00pm",
    days: [1, 3],
  },
];

export function potToListing(pot: CatalogPot, day: string): Listing {
  return {
    id: `${pot.id}_${day}`,
    cookId: pot.cookId,
    cookName: pot.cookName,
    cookLine: pot.cookLine,
    neighborhood: pot.neighborhood,
    island: pot.island,
    title: pot.title,
    description: pot.description,
    priceCents: pot.priceCents,
    servingsLeft: pot.servingsLeft,
    tags: pot.tags,
    pepper: pot.pepper,
    daypart: pot.daypart,
    visual: pot.visual,
    availableDate: day,
    pickupWindow: pot.pickupWindow,
    seeded: true,
  };
}
