import type { TrackFamily } from "./track-family";

export type TrackDef = {
  slug: string;
  role: string;
  setting: string;
  blurb: string;
  family: TrackFamily;
  themes: [string, string, string, string, string];
};

export const TRACK_DEFS: TrackDef[] = [
  // Healthcare and Medicine
  {
    slug: 'registered-nurse',
    role: 'Registered Nurse',
    setting: 'Acute care hospital unit',
    blurb: 'Clinical judgment, patient safety, handoffs, and calm under acuity.',
    family: 'Healthcare and Medicine',
    themes: ['triage', 'handoff', 'acuity', 'medication safety', 'rapid response'],
  },
  {
    slug: 'pharmacist',
    role: 'Pharmacist',
    setting: 'Hospital or retail pharmacy',
    blurb: 'Drug interactions, counseling, verification, and inventory under pressure.',
    family: 'Healthcare and Medicine',
    themes: ['verification', 'interactions', 'counseling', 'sterile compounding', 'prior auth'],
  },
  {
    slug: 'physician-assistant',
    role: 'Physician Assistant',
    setting: 'Outpatient clinic or hospital service',
    blurb: 'Assessment, differential, orders, and team-based care.',
    family: 'Healthcare and Medicine',
    themes: ['differential', 'orders', 'shared visits', 'documentation', 'escalation'],
  },
  {
    slug: 'physical-therapist',
    role: 'Physical Therapist',
    setting: 'Outpatient rehab clinic',
    blurb: 'Functional goals, home programs, and progress under insurance limits.',
    family: 'Healthcare and Medicine',
    themes: ['functional goals', 'HEP adherence', 'prior auth', 'gait training', 'discharge'],
  },
  {
    slug: 'medical-assistant',
    role: 'Medical Assistant',
    setting: 'Primary care office',
    blurb: 'Rooming, vitals, EHR, and patient flow without dropping safety.',
    family: 'Healthcare and Medicine',
    themes: ['rooming', 'vitals', 'EHR', 'patient flow', 'vaccine admin'],
  },
  {
    slug: 'occupational-therapist',
    role: 'Occupational Therapist',
    setting: 'Inpatient rehab or outpatient OT',
    blurb: 'ADLs, adaptive equipment, and discharge readiness.',
    family: 'Healthcare and Medicine',
    themes: ['ADLs', 'adaptive equipment', 'cognition', 'caregiver training', 'discharge'],
  },
  {
    slug: 'dental-hygienist',
    role: 'Dental Hygienist',
    setting: 'Dental practice',
    blurb: 'Prophy, perio charting, radiographs, and patient education.',
    family: 'Healthcare and Medicine',
    themes: ['perio charting', 'radiographs', 'scaling', 'oral hygiene', 'infection control'],
  },
  {
    slug: 'radiologic-technologist',
    role: 'Radiologic Technologist',
    setting: 'Hospital imaging department',
    blurb: 'Positioning, dose, contrast, and trauma workflow.',
    family: 'Healthcare and Medicine',
    themes: ['positioning', 'ALARA', 'contrast', 'trauma', 'PACS'],
  },
  {
    slug: 'respiratory-therapist',
    role: 'Respiratory Therapist',
    setting: 'ICU / respiratory care',
    blurb: 'Vent management, ABGs, and acute respiratory distress.',
    family: 'Healthcare and Medicine',
    themes: ['ventilator', 'ABG', 'airway', 'weaning', 'codes'],
  },
  {
    slug: 'nurse-practitioner',
    role: 'Nurse Practitioner',
    setting: 'Primary or specialty clinic',
    blurb: 'Independent panels, diagnostics, and care plans.',
    family: 'Healthcare and Medicine',
    themes: ['panel management', 'prescribing', 'diagnostics', 'follow-up', 'referrals'],
  },
  {
    slug: 'speech-language-pathologist',
    role: 'Speech-Language Pathologist',
    setting: 'School or medical SLP setting',
    blurb: 'Swallow, speech, and language goals with measurable progress.',
    family: 'Healthcare and Medicine',
    themes: ['swallow eval', 'articulation', 'IEP goals', 'AAC', 'caregiver coaching'],
  },
  {
    slug: 'surgical-technologist',
    role: 'Surgical Technologist',
    setting: 'Operating room',
    blurb: 'Sterile field, counts, and anticipation of the surgeon.',
    family: 'Healthcare and Medicine',
    themes: ['sterile field', 'counts', 'instrumentation', 'turnover', 'timeout'],
  },
  {
    slug: 'dietitian',
    role: 'Registered Dietitian',
    setting: 'Hospital nutrition services',
    blurb: 'Medical nutrition therapy and interdisciplinary rounds.',
    family: 'Healthcare and Medicine',
    themes: ['MNT', 'malnutrition', 'TF/TPN', 'education', 'rounds'],
  },
  {
    slug: 'emergency-medical-technician',
    role: 'Emergency Medical Technician',
    setting: 'Ambulance / EMS',
    blurb: 'Scene safety, BLS, and concise hospital handoff.',
    family: 'Healthcare and Medicine',
    themes: ['scene safety', 'BLS', 'vitals trends', 'handoff', 'destination'],
  },
  {
    slug: 'licensed-practical-nurse',
    role: 'Licensed Practical Nurse',
    setting: 'Long-term care or clinic',
    blurb: 'Medication passes, wound care, and escalation to the RN/MD.',
    family: 'Healthcare and Medicine',
    themes: ['med pass', 'wound care', 'vitals', 'escalation', 'documentation'],
  },
  {
    slug: 'phlebotomist',
    role: 'Phlebotomist',
    setting: 'Hospital lab draw team',
    blurb: 'Difficult sticks, labeling, and patient comfort under volume.',
    family: 'Healthcare and Medicine',
    themes: ['venipuncture', 'labeling', 'order of draw', 'difficult sticks', 'specimen integrity'],
  },
  {
    slug: 'health-information-technician',
    role: 'Health Information Technician',
    setting: 'Health information management',
    blurb: 'Coding accuracy, privacy, and release-of-information requests.',
    family: 'Healthcare and Medicine',
    themes: ['coding', 'HIPAA', 'ROI', 'chart completeness', 'audits'],
  },
  {
    slug: 'home-health-aide',
    role: 'Home Health Aide',
    setting: 'In-home care agency',
    blurb: 'ADLs, safety in the home, and reporting changes promptly.',
    family: 'Healthcare and Medicine',
    themes: ['ADLs', 'fall risk', 'vitals reporting', 'boundaries', 'care plan'],
  },
  {
    slug: 'medical-office-manager',
    role: 'Medical Office Manager',
    setting: 'Multi-provider clinic',
    blurb: 'Staffing, scheduling, revenue cycle, and patient experience.',
    family: 'Healthcare and Medicine',
    themes: ['scheduling', 'staffing', 'revenue cycle', 'complaints', 'compliance'],
  },
  {
    slug: 'clinical-nurse-educator',
    role: 'Clinical Nurse Educator',
    setting: 'Hospital education department',
    blurb: 'Competency, simulation, and practice change adoption.',
    family: 'Healthcare and Medicine',
    themes: ['competency', 'simulation', 'precepting', 'protocols', 'evaluation'],
  },
  // Information Technology
  {
    slug: 'software-engineer',
    role: 'Software Engineer',
    setting: 'Series B product company',
    blurb: 'Ownership stories, live coding, debugging, and design judgment.',
    family: 'Information Technology',
    themes: ['ownership', 'debugging', 'APIs', 'testing', 'incidents'],
  },
  {
    slug: 'product-manager',
    role: 'Product Manager',
    setting: 'B2B SaaS product team',
    blurb: 'Prioritization, specs, tradeoffs, and stakeholder alignment.',
    family: 'Information Technology',
    themes: ['prioritization', 'roadmaps', 'metrics', 'discovery', 'tradeoffs'],
  },
  {
    slug: 'data-analyst',
    role: 'Data Analyst',
    setting: 'Growth analytics team',
    blurb: 'SQL, experimentation, dashboards, and actionable insights.',
    family: 'Information Technology',
    themes: ['SQL', 'experimentation', 'dashboards', 'funnels', 'data quality'],
  },
  {
    slug: 'devops-sre',
    role: 'DevOps / SRE',
    setting: 'Platform reliability team',
    blurb: 'SLOs, on-call, CI/CD, and incident culture.',
    family: 'Information Technology',
    themes: ['SLOs', 'on-call', 'CI/CD', 'observability', 'toil'],
  },
  {
    slug: 'cybersecurity-analyst',
    role: 'Cybersecurity Analyst',
    setting: 'Security operations center',
    blurb: 'Detection, triage, and containment without panic.',
    family: 'Information Technology',
    themes: ['SIEM', 'phishing', 'containment', 'IAM', 'threat intel'],
  },
  {
    slug: 'cloud-architect',
    role: 'Cloud Architect',
    setting: 'Enterprise cloud center of excellence',
    blurb: 'Landing zones, cost, and multi-account design.',
    family: 'Information Technology',
    themes: ['landing zones', 'IAM', 'cost', 'networking', 'Well-Architected'],
  },
  {
    slug: 'qa-engineer',
    role: 'QA Engineer',
    setting: 'Product quality team',
    blurb: 'Test strategy, automation, and risk-based coverage.',
    family: 'Information Technology',
    themes: ['test plans', 'automation', 'regression', 'risk-based', 'bug triage'],
  },
  {
    slug: 'data-engineer',
    role: 'Data Engineer',
    setting: 'Data platform team',
    blurb: 'Pipelines, warehousing, and reliable schemas.',
    family: 'Information Technology',
    themes: ['ETL/ELT', 'warehouses', 'orchestration', 'schema', 'SLAs'],
  },
  {
    slug: 'machine-learning-engineer',
    role: 'Machine Learning Engineer',
    setting: 'ML platform / applied ML team',
    blurb: 'Training, serving, evaluation, and drift.',
    family: 'Information Technology',
    themes: ['training', 'serving', 'evaluation', 'feature stores', 'drift'],
  },
  {
    slug: 'frontend-engineer',
    role: 'Frontend Engineer',
    setting: 'Consumer web product team',
    blurb: 'UI systems, performance, and accessibility.',
    family: 'Information Technology',
    themes: ['React', 'performance', 'a11y', 'state', 'design systems'],
  },
  {
    slug: 'backend-engineer',
    role: 'Backend Engineer',
    setting: 'API-heavy product org',
    blurb: 'Services, data models, and reliability under load.',
    family: 'Information Technology',
    themes: ['services', 'databases', 'caching', 'auth', 'queues'],
  },
  {
    slug: 'mobile-engineer',
    role: 'Mobile Engineer',
    setting: 'iOS/Android product team',
    blurb: 'Release cadence, offline, and store constraints.',
    family: 'Information Technology',
    themes: ['release trains', 'offline', 'crash rates', 'push', 'store review'],
  },
  {
    slug: 'it-support-specialist',
    role: 'IT Support Specialist',
    setting: 'Corporate IT help desk',
    blurb: 'Tickets, escalation, and calm user communication.',
    family: 'Information Technology',
    themes: ['tickets', 'imaging', 'identity', 'escalation', 'SLA'],
  },
  {
    slug: 'database-administrator',
    role: 'Database Administrator',
    setting: 'Enterprise data ops',
    blurb: 'Backups, performance, and change control.',
    family: 'Information Technology',
    themes: ['backups', 'replication', 'indexes', 'change control', 'DR'],
  },
  {
    slug: 'systems-administrator',
    role: 'Systems Administrator',
    setting: 'Internal infrastructure team',
    blurb: 'Servers, patching, and access hygiene.',
    family: 'Information Technology',
    themes: ['patching', 'monitoring', 'access', 'automation', 'uptime'],
  },
  {
    slug: 'network-engineer',
    role: 'Network Engineer',
    setting: 'Enterprise networking',
    blurb: 'Routing, segmentation, and outage diagnosis.',
    family: 'Information Technology',
    themes: ['routing', 'firewalls', 'VPN', 'segmentation', 'packet capture'],
  },
  {
    slug: 'solutions-architect',
    role: 'Solutions Architect',
    setting: 'Enterprise pre-sales / SA',
    blurb: 'Requirements, demos, and credible technical proposals.',
    family: 'Information Technology',
    themes: ['discovery', 'demos', 'integration', 'risks', 'POCs'],
  },
  {
    slug: 'technical-program-manager',
    role: 'Technical Program Manager',
    setting: 'Cross-org platform programs',
    blurb: 'Dependencies, risk, and delivery across teams.',
    family: 'Information Technology',
    themes: ['dependencies', 'RAID', 'milestones', 'stakeholder sync', 'risk'],
  },
  {
    slug: 'platform-engineer',
    role: 'Platform Engineer',
    setting: 'Internal developer platform',
    blurb: 'Self-serve tooling, paved roads, and DX metrics.',
    family: 'Information Technology',
    themes: ['paved roads', 'IDP', 'templates', 'guardrails', 'DX'],
  },
  {
    slug: 'scrum-master',
    role: 'Scrum Master / Agile Coach',
    setting: 'Agile delivery team',
    blurb: 'Facilitation, impediments, and healthy ceremonies.',
    family: 'Information Technology',
    themes: ['impediments', 'retros', 'velocity', 'facilitation', 'coaching'],
  },
  // Business and Finance
  {
    slug: 'finance-fpa',
    role: 'Finance / FP&A',
    setting: 'Corporate FP&A team',
    blurb: 'Forecasts, variance, and partnering with operators.',
    family: 'Business and Finance',
    themes: ['forecast', 'variance', 'driver models', 'board packs', 'scenarios'],
  },
  {
    slug: 'management-consulting',
    role: 'Management Consultant',
    setting: 'Strategy consulting firm',
    blurb: 'Structured problem-solving, slides, and client presence.',
    family: 'Business and Finance',
    themes: ['issue trees', 'MECE', 'hypotheses', 'workplans', 'synthesis'],
  },
  {
    slug: 'investment-banking',
    role: 'Investment Banking Analyst',
    setting: 'IBD coverage or product group',
    blurb: 'Models, process, and calm under live deals.',
    family: 'Business and Finance',
    themes: ['models', 'comps', 'process letters', 'diligence', 'pitches'],
  },
  {
    slug: 'business-analyst',
    role: 'Business Analyst',
    setting: 'Internal transformation office',
    blurb: 'Requirements, process maps, and UAT.',
    family: 'Business and Finance',
    themes: ['requirements', 'process maps', 'UAT', 'stakeholders', 'gaps'],
  },
  {
    slug: 'project-manager',
    role: 'Project Manager',
    setting: 'PMO / delivery organization',
    blurb: 'Scope, risk, and cross-functional execution.',
    family: 'Business and Finance',
    themes: ['scope', 'RAID', 'milestones', 'change control', 'status'],
  },
  {
    slug: 'accounting-audit',
    role: 'Accounting / Audit',
    setting: 'Public accounting or corporate accounting',
    blurb: 'Controls, close, and audit evidence.',
    family: 'Business and Finance',
    themes: ['close', 'controls', 'evidence', 'reconciliations', 'GAAP'],
  },
  {
    slug: 'corporate-strategy',
    role: 'Corporate Strategy',
    setting: 'Corporate strategy team',
    blurb: 'Market scans, M&A screening, and exec decks.',
    family: 'Business and Finance',
    themes: ['market sizing', 'M&A', 'portfolios', 'OKRs', 'exec decks'],
  },
  {
    slug: 'risk-compliance',
    role: 'Risk & Compliance',
    setting: 'Enterprise risk / compliance',
    blurb: 'Policies, testing, and issue remediation.',
    family: 'Business and Finance',
    themes: ['policies', 'KRIs', 'testing', 'issues', 'regulators'],
  },
  {
    slug: 'general-manager',
    role: 'General Manager',
    setting: 'P&L business unit',
    blurb: 'Ownership of revenue, cost, and people.',
    family: 'Business and Finance',
    themes: ['P&L', 'pricing', 'ops', 'talent', 'customers'],
  },
  {
    slug: 'entrepreneur',
    role: 'Entrepreneur / Founder',
    setting: 'Early-stage venture',
    blurb: 'Customer discovery, runway, and hard prioritization.',
    family: 'Business and Finance',
    themes: ['discovery', 'runway', 'MVP', 'fundraising', 'hiring'],
  },
  {
    slug: 'operations',
    role: 'Operations Manager',
    setting: 'Scaled operations org',
    blurb: 'Throughput, quality, and SOP adoption.',
    family: 'Business and Finance',
    themes: ['throughput', 'SOPs', 'capacity', 'quality', 'vendors'],
  },
  {
    slug: 'financial-analyst',
    role: 'Financial Analyst',
    setting: 'Corporate finance desk',
    blurb: 'Models, reporting, and decision support.',
    family: 'Business and Finance',
    themes: ['models', 'reporting', 'KPIs', 'ad-hoc asks', 'accuracy'],
  },
  {
    slug: 'treasury-analyst',
    role: 'Treasury Analyst',
    setting: 'Corporate treasury',
    blurb: 'Cash, liquidity, and bank relationships.',
    family: 'Business and Finance',
    themes: ['cash', 'liquidity', 'FX', 'banking', 'forecasts'],
  },
  {
    slug: 'internal-auditor',
    role: 'Internal Auditor',
    setting: 'Internal audit department',
    blurb: 'Risk-based audits and constructive findings.',
    family: 'Business and Finance',
    themes: ['risk assessment', 'fieldwork', 'findings', 'remediation', 'IIA'],
  },
  {
    slug: 'tax-accountant',
    role: 'Tax Accountant',
    setting: 'Corporate tax or public tax practice',
    blurb: 'Returns, provisions, and controversy readiness.',
    family: 'Business and Finance',
    themes: ['provisions', 'returns', 'credits', 'nexus', 'controversy'],
  },
  {
    slug: 'controller',
    role: 'Controller',
    setting: 'Mid-market finance leadership',
    blurb: 'Close ownership, reporting, and team leadership.',
    family: 'Business and Finance',
    themes: ['close', 'reporting', 'team', 'controls', 'systems'],
  },
  {
    slug: 'commercial-banker',
    role: 'Commercial Banker',
    setting: 'Middle-market banking',
    blurb: 'Credit, relationships, and portfolio risk.',
    family: 'Business and Finance',
    themes: ['credit', 'covenants', 'portfolio', 'deposits', 'cross-sell'],
  },
  {
    slug: 'actuarial-analyst',
    role: 'Actuarial Analyst',
    setting: 'Insurance actuarial team',
    blurb: 'Pricing, reserving, and model assumptions.',
    family: 'Business and Finance',
    themes: ['pricing', 'reserves', 'assumptions', 'loss triangles', 'reg filings'],
  },
  {
    slug: 'private-equity-associate',
    role: 'Private Equity Associate',
    setting: 'PE investment team',
    blurb: 'Deal screens, diligence, and portfolio support.',
    family: 'Business and Finance',
    themes: ['screens', 'LBO', 'diligence', 'IC memos', 'portfolio'],
  },
  {
    slug: 'venture-capital-associate',
    role: 'Venture Capital Associate',
    setting: 'Early-stage VC firm',
    blurb: 'Sourcing, diligence, and founder evaluation.',
    family: 'Business and Finance',
    themes: ['sourcing', 'diligence', 'markets', 'founder fit', 'memos'],
  },
  // Education and Training
  {
    slug: 'high-school-teacher',
    role: 'High School Teacher',
    setting: 'Public high school',
    blurb: 'Classroom management, standards, and parent partnership.',
    family: 'Education and Training',
    themes: ['standards', 'classroom management', 'differentiation', 'assessment', 'parents'],
  },
  {
    slug: 'instructional-designer',
    role: 'Instructional Designer',
    setting: 'Corporate L&D or edtech',
    blurb: 'Objectives, modalities, and measurable learning.',
    family: 'Education and Training',
    themes: ['objectives', 'storyboarding', 'modalities', 'assessment', 'LMS'],
  },
  {
    slug: 'elementary-teacher',
    role: 'Elementary Teacher',
    setting: 'Elementary school',
    blurb: 'Literacy, routines, and family communication.',
    family: 'Education and Training',
    themes: ['literacy', 'routines', 'SEL', 'centers', 'families'],
  },
  {
    slug: 'special-education-teacher',
    role: 'Special Education Teacher',
    setting: 'Inclusive / resource classroom',
    blurb: 'IEPs, accommodations, and advocacy with care.',
    family: 'Education and Training',
    themes: ['IEPs', 'accommodations', 'progress monitoring', 'co-teaching', 'behavior'],
  },
  {
    slug: 'school-counselor',
    role: 'School Counselor',
    setting: 'K-12 counseling office',
    blurb: 'Scheduling, crises, and college/career guidance.',
    family: 'Education and Training',
    themes: ['scheduling', 'crisis', '504/IEP', 'college', 'groups'],
  },
  {
    slug: 'academic-advisor',
    role: 'Academic Advisor',
    setting: 'College advising center',
    blurb: 'Degree plans, holds, and student belonging.',
    family: 'Education and Training',
    themes: ['degree plans', 'holds', 'retention', 'referrals', 'policies'],
  },
  {
    slug: 'corporate-trainer',
    role: 'Corporate Trainer',
    setting: 'Enterprise learning team',
    blurb: 'Facilitation, practice, and transfer to the job.',
    family: 'Education and Training',
    themes: ['facilitation', 'practice', 'transfer', 'feedback', 'metrics'],
  },
  {
    slug: 'curriculum-coordinator',
    role: 'Curriculum Coordinator',
    setting: 'District academic office',
    blurb: 'Alignment, adoption, and teacher support.',
    family: 'Education and Training',
    themes: ['alignment', 'adoption', 'PD', 'materials', 'equity'],
  },
  {
    slug: 'school-principal',
    role: 'School Principal',
    setting: 'K-12 campus leadership',
    blurb: 'Instructional leadership, culture, and operations.',
    family: 'Education and Training',
    themes: ['instruction', 'culture', 'staffing', 'safety', 'community'],
  },
  {
    slug: 'librarian',
    role: 'Librarian / Media Specialist',
    setting: 'School or public library',
    blurb: 'Collections, information literacy, and access.',
    family: 'Education and Training',
    themes: ['collections', 'info literacy', 'programming', 'access', 'catalog'],
  },
  {
    slug: 'esl-teacher',
    role: 'ESL / ELL Teacher',
    setting: 'Language learner program',
    blurb: 'Language acquisition and content access.',
    family: 'Education and Training',
    themes: ['scaffolding', 'WIDA', 'content access', 'families', 'assessment'],
  },
  {
    slug: 'early-childhood-educator',
    role: 'Early Childhood Educator',
    setting: 'Preschool / Pre-K',
    blurb: 'Play-based learning, safety, and family trust.',
    family: 'Education and Training',
    themes: ['play-based', 'routines', 'safety', 'observation', 'families'],
  },
  {
    slug: 'college-professor',
    role: 'College Professor',
    setting: 'Undergraduate department',
    blurb: 'Teaching, research balance, and student support.',
    family: 'Education and Training',
    themes: ['syllabus', 'assessment', 'office hours', 'research', 'service'],
  },
  {
    slug: 'admissions-counselor',
    role: 'Admissions Counselor',
    setting: 'College admissions office',
    blurb: 'Recruiting, yield, and ethical counseling.',
    family: 'Education and Training',
    themes: ['recruiting', 'yield', 'events', 'CRM', 'ethics'],
  },
  {
    slug: 'education-technology-specialist',
    role: 'Education Technology Specialist',
    setting: 'District edtech team',
    blurb: 'Tool selection, PD, and data privacy.',
    family: 'Education and Training',
    themes: ['tools', 'PD', 'privacy', 'integration', 'support'],
  },
  {
    slug: 'adult-education-instructor',
    role: 'Adult Education Instructor',
    setting: 'Adult learning center',
    blurb: 'Workforce skills and respectful adult pedagogy.',
    family: 'Education and Training',
    themes: ['andragogy', 'workforce', 'assessment', 'retention', 'flexibility'],
  },
  {
    slug: 'school-psychologist',
    role: 'School Psychologist',
    setting: 'District psychological services',
    blurb: 'Assessment, MTSS, and crisis collaboration.',
    family: 'Education and Training',
    themes: ['assessment', 'MTSS', 'IEP', 'crisis', 'consultation'],
  },
  {
    slug: 'teaching-assistant',
    role: 'Teaching Assistant',
    setting: 'Classroom support role',
    blurb: 'Small groups, behavior support, and teacher partnership.',
    family: 'Education and Training',
    themes: ['small groups', 'behavior', 'prep', 'inclusion', 'communication'],
  },
  {
    slug: 'athletic-coach',
    role: 'Athletic Coach',
    setting: 'School athletics program',
    blurb: 'Practice design, character, and eligibility.',
    family: 'Education and Training',
    themes: ['practice plans', 'conditioning', 'eligibility', 'parents', 'safety'],
  },
  {
    slug: 'literacy-specialist',
    role: 'Literacy Specialist',
    setting: 'Reading intervention program',
    blurb: 'Diagnostics, interventions, and teacher coaching.',
    family: 'Education and Training',
    themes: ['diagnostics', 'intervention', 'progress', 'coaching', 'phonics'],
  },
  // Engineering and Architecture
  {
    slug: 'civil-engineer',
    role: 'Civil Engineer',
    setting: 'Civil / infrastructure firm',
    blurb: 'Codes, constructability, and stakeholder constraints.',
    family: 'Engineering and Architecture',
    themes: ['codes', 'hydraulics', 'CAD', 'constructability', 'permits'],
  },
  {
    slug: 'mechanical-engineer',
    role: 'Mechanical Engineer',
    setting: 'Product or plant engineering',
    blurb: 'Thermodynamics, GD&T, and design reviews.',
    family: 'Engineering and Architecture',
    themes: ['GD&T', 'FEA', 'thermo', 'DFM', 'tolerance'],
  },
  {
    slug: 'electrical-engineer',
    role: 'Electrical Engineer',
    setting: 'Power or electronics org',
    blurb: 'Circuits, safety, and verification.',
    family: 'Engineering and Architecture',
    themes: ['circuits', 'power', 'EMI', 'safety', 'verification'],
  },
  {
    slug: 'chemical-engineer',
    role: 'Chemical Engineer',
    setting: 'Process plant / chemicals',
    blurb: 'Mass balance, scale-up, and process safety.',
    family: 'Engineering and Architecture',
    themes: ['mass balance', 'scale-up', 'HAZOP', 'yield', 'utilities'],
  },
  {
    slug: 'aerospace-engineer',
    role: 'Aerospace Engineer',
    setting: 'Aerospace OEM or supplier',
    blurb: 'Requirements, margins, and certification rigor.',
    family: 'Engineering and Architecture',
    themes: ['requirements', 'margins', 'loads', 'certification', 'FMEA'],
  },
  {
    slug: 'industrial-engineer',
    role: 'Industrial Engineer',
    setting: 'Manufacturing / ops engineering',
    blurb: 'Time study, layout, and waste reduction.',
    family: 'Engineering and Architecture',
    themes: ['time study', 'layout', 'Lean', 'capacity', 'ergonomics'],
  },
  {
    slug: 'biomedical-engineer',
    role: 'Biomedical Engineer',
    setting: 'Med device company',
    blurb: 'Design controls, V&V, and clinical constraints.',
    family: 'Engineering and Architecture',
    themes: ['design controls', 'V&V', 'ISO 13485', 'usability', 'biocompatibility'],
  },
  {
    slug: 'structural-engineer',
    role: 'Structural Engineer',
    setting: 'Structural consulting firm',
    blurb: 'Loads, detailing, and peer review.',
    family: 'Engineering and Architecture',
    themes: ['loads', 'steel/concrete', 'detailing', 'peer review', 'field issues'],
  },
  {
    slug: 'environmental-engineer',
    role: 'Environmental Engineer',
    setting: 'Environmental consulting',
    blurb: 'Permits, remediation, and compliance sampling.',
    family: 'Engineering and Architecture',
    themes: ['permits', 'remediation', 'sampling', 'modeling', 'reporting'],
  },
  {
    slug: 'architect',
    role: 'Architect',
    setting: 'Architecture studio',
    blurb: 'Program, code, and client design intent.',
    family: 'Engineering and Architecture',
    themes: ['program', 'code', 'schematics', 'CD sets', 'CA'],
  },
  {
    slug: 'landscape-architect',
    role: 'Landscape Architect',
    setting: 'Landscape architecture firm',
    blurb: 'Site, stormwater, and planting intent.',
    family: 'Engineering and Architecture',
    themes: ['site', 'grading', 'planting', 'stormwater', 'sustainability'],
  },
  {
    slug: 'urban-planner',
    role: 'Urban Planner',
    setting: 'City planning or consulting',
    blurb: 'Zoning, engagement, and land-use tradeoffs.',
    family: 'Engineering and Architecture',
    themes: ['zoning', 'engagement', 'GIS', 'housing', 'mobility'],
  },
  {
    slug: 'materials-engineer',
    role: 'Materials Engineer',
    setting: 'Materials R&D / failure analysis',
    blurb: 'Selection, testing, and failure modes.',
    family: 'Engineering and Architecture',
    themes: ['selection', 'testing', 'microstructure', 'corrosion', 'failure'],
  },
  {
    slug: 'systems-engineer',
    role: 'Systems Engineer',
    setting: 'Complex systems program',
    blurb: 'Requirements flowdown and interface control.',
    family: 'Engineering and Architecture',
    themes: ['requirements', 'interfaces', 'V&V', 'trades', 'MBSE'],
  },
  {
    slug: 'hardware-engineer',
    role: 'Hardware Engineer',
    setting: 'Electronics hardware team',
    blurb: 'Schematics, bring-up, and DFM with CM.',
    family: 'Engineering and Architecture',
    themes: ['schematics', 'bring-up', 'DFM', 'BOM', 'EMC'],
  },
  {
    slug: 'robotics-engineer',
    role: 'Robotics Engineer',
    setting: 'Robotics / automation team',
    blurb: 'Perception, controls, and safety cells.',
    family: 'Engineering and Architecture',
    themes: ['controls', 'perception', 'kinematics', 'safety', 'integration'],
  },
  {
    slug: 'geotechnical-engineer',
    role: 'Geotechnical Engineer',
    setting: 'Geotech consulting',
    blurb: 'Borings, foundations, and construction support.',
    family: 'Engineering and Architecture',
    themes: ['borings', 'foundations', 'settlement', 'slopes', 'reports'],
  },
  {
    slug: 'petroleum-engineer',
    role: 'Petroleum Engineer',
    setting: 'Upstream energy company',
    blurb: 'Reservoirs, wells, and production optimization.',
    family: 'Engineering and Architecture',
    themes: ['reservoirs', 'wells', 'production', 'economics', 'HSE'],
  },
  {
    slug: 'nuclear-engineer',
    role: 'Nuclear Engineer',
    setting: 'Nuclear plant / lab',
    blurb: 'Safety culture, procedures, and analysis rigor.',
    family: 'Engineering and Architecture',
    themes: ['procedures', 'safety culture', 'analysis', 'licensing', 'ops'],
  },
  {
    slug: 'hvac-design-engineer',
    role: 'HVAC Design Engineer',
    setting: 'MEP consulting firm',
    blurb: 'Loads, equipment selection, and energy codes.',
    family: 'Engineering and Architecture',
    themes: ['loads', 'equipment', 'ductwork', 'energy codes', 'commissioning'],
  },
  // Construction and Trades
  {
    slug: 'electrician',
    role: 'Electrician',
    setting: 'Commercial electrical contractor',
    blurb: 'Code, troubleshooting, and safe energization.',
    family: 'Construction and Trades',
    themes: ['NEC', 'troubleshooting', 'panels', 'lockout', 'rough-in'],
  },
  {
    slug: 'construction-superintendent',
    role: 'Construction Superintendent',
    setting: 'General contractor site leadership',
    blurb: 'Schedule, safety, and trade coordination.',
    family: 'Construction and Trades',
    themes: ['schedule', 'safety', 'trades', 'RFIs', 'quality'],
  },
  {
    slug: 'plumber',
    role: 'Plumber',
    setting: 'Plumbing contractor',
    blurb: 'Fixtures, drains, and code inspections.',
    family: 'Construction and Trades',
    themes: ['fixtures', 'drains', 'water heaters', 'code', 'diagnostics'],
  },
  {
    slug: 'carpenter',
    role: 'Carpenter',
    setting: 'Framing / finish carpentry',
    blurb: 'Layout, tolerances, and production pace.',
    family: 'Construction and Trades',
    themes: ['layout', 'framing', 'finish', 'tools', 'plans'],
  },
  {
    slug: 'hvac-technician',
    role: 'HVAC Technician',
    setting: 'HVAC service company',
    blurb: 'Diagnostics, refrigerant, and customer clarity.',
    family: 'Construction and Trades',
    themes: ['diagnostics', 'refrigerant', 'airflow', 'controls', 'safety'],
  },
  {
    slug: 'welder',
    role: 'Welder',
    setting: 'Fab shop or field welding',
    blurb: 'Procedure, quality, and fit-up.',
    family: 'Construction and Trades',
    themes: ['WPS', 'fit-up', 'NDT', 'positions', 'safety'],
  },
  {
    slug: 'heavy-equipment-operator',
    role: 'Heavy Equipment Operator',
    setting: 'Civil / earthwork site',
    blurb: 'Grade, machine care, and site awareness.',
    family: 'Construction and Trades',
    themes: ['grade', 'excavation', 'spotters', 'maintenance', 'safety'],
  },
  {
    slug: 'painter',
    role: 'Painter',
    setting: 'Commercial painting contractor',
    blurb: 'Prep, coatings, and punch quality.',
    family: 'Construction and Trades',
    themes: ['prep', 'coatings', 'masking', 'schedules', 'punch'],
  },
  {
    slug: 'mason',
    role: 'Mason',
    setting: 'Masonry contractor',
    blurb: 'Layout, mortar, and structural openings.',
    family: 'Construction and Trades',
    themes: ['layout', 'mortar', 'block', 'openings', 'weather'],
  },
  {
    slug: 'roofing-contractor',
    role: 'Roofing Specialist',
    setting: 'Commercial roofing crew',
    blurb: 'Systems, weather windows, and leak diagnosis.',
    family: 'Construction and Trades',
    themes: ['membranes', 'flashings', 'leaks', 'fall protection', 'warranties'],
  },
  {
    slug: 'project-estimator',
    role: 'Construction Estimator',
    setting: 'GC estimating desk',
    blurb: 'Takeoffs, risk, and bid strategy.',
    family: 'Construction and Trades',
    themes: ['takeoffs', 'subs', 'contingency', 'clarifications', 'bid day'],
  },
  {
    slug: 'site-safety-officer',
    role: 'Site Safety Officer',
    setting: 'Jobsite safety leadership',
    blurb: 'Hazards, toolbox talks, and stop-work authority.',
    family: 'Construction and Trades',
    themes: ['hazards', 'toolbox', 'PPE', 'incidents', 'OSHA'],
  },
  {
    slug: 'ironworker',
    role: 'Ironworker',
    setting: 'Structural steel erection',
    blurb: 'Rigging, connections, and height safety.',
    family: 'Construction and Trades',
    themes: ['rigging', 'bolting', 'decking', 'crane', 'fall protection'],
  },
  {
    slug: 'sheet-metal-worker',
    role: 'Sheet Metal Worker',
    setting: 'Sheet metal / duct shop',
    blurb: 'Fabrication, install, and shop drawings.',
    family: 'Construction and Trades',
    themes: ['fabrication', 'duct', 'shop drawings', 'install', 'sealing'],
  },
  {
    slug: 'construction-project-manager',
    role: 'Construction Project Manager',
    setting: 'GC project office',
    blurb: 'Contracts, cost, and owner communication.',
    family: 'Construction and Trades',
    themes: ['contracts', 'cost', 'schedule', 'changes', 'closeout'],
  },
  {
    slug: 'building-inspector',
    role: 'Building Inspector',
    setting: 'Municipal inspection department',
    blurb: 'Code enforcement with clear coaching.',
    family: 'Construction and Trades',
    themes: ['code', 'inspections', 'permits', 'violations', 'docs'],
  },
  {
    slug: 'pipefitter',
    role: 'Pipefitter',
    setting: 'Industrial / mechanical contractor',
    blurb: 'Isometrics, hydrotests, and system integrity.',
    family: 'Construction and Trades',
    themes: ['isometrics', 'welding', 'hydrotest', 'hangers', 'specs'],
  },
  {
    slug: 'millwright',
    role: 'Millwright',
    setting: 'Industrial maintenance / install',
    blurb: 'Alignment, rebuilds, and downtime pressure.',
    family: 'Construction and Trades',
    themes: ['alignment', 'rebuilds', 'bearings', 'rigging', 'PM'],
  },
  {
    slug: 'crane-operator',
    role: 'Crane Operator',
    setting: 'Heavy lift operations',
    blurb: 'Lift plans, signals, and exclusion zones.',
    family: 'Construction and Trades',
    themes: ['lift plans', 'signals', 'capacity', 'wind', 'exclusion'],
  },
  {
    slug: 'drywall-installer',
    role: 'Drywall Installer',
    setting: 'Interior finishes contractor',
    blurb: 'Layout, hanging, and finish levels.',
    family: 'Construction and Trades',
    themes: ['layout', 'hanging', 'taping', 'levels', 'schedule'],
  },
  // Arts and Communication
  {
    slug: 'ux-designer',
    role: 'UX Designer',
    setting: 'Product design team',
    blurb: 'Research, flows, and usability judgment.',
    family: 'Arts and Communication',
    themes: ['research', 'flows', 'prototypes', 'usability', 'critique'],
  },
  {
    slug: 'graphic-designer',
    role: 'Graphic Designer',
    setting: 'Brand / marketing design studio',
    blurb: 'Typography, systems, and stakeholder feedback.',
    family: 'Arts and Communication',
    themes: ['typography', 'brand', 'layout', 'feedback', 'production'],
  },
  {
    slug: 'corporate-communications',
    role: 'Corporate Communications',
    setting: 'Internal / external comms team',
    blurb: 'Messaging, crises, and executive voice.',
    family: 'Arts and Communication',
    themes: ['messaging', 'crisis', 'channels', 'executives', 'media'],
  },
  {
    slug: 'content-producer',
    role: 'Content Producer',
    setting: 'Media / content studio',
    blurb: 'Pipelines, deadlines, and quality under volume.',
    family: 'Arts and Communication',
    themes: ['pipeline', 'briefs', 'editing', 'SEO', 'deadlines'],
  },
  {
    slug: 'copywriter',
    role: 'Copywriter',
    setting: 'Agency or in-house brand',
    blurb: 'Voice, conversion, and revision discipline.',
    family: 'Arts and Communication',
    themes: ['voice', 'hooks', 'CTA', 'revisions', 'briefs'],
  },
  {
    slug: 'journalist',
    role: 'Journalist',
    setting: 'Newsroom',
    blurb: 'Sourcing, accuracy, and fair framing under deadline.',
    family: 'Arts and Communication',
    themes: ['sourcing', 'accuracy', 'leads', 'ethics', 'deadline'],
  },
  {
    slug: 'public-relations-specialist',
    role: 'Public Relations Specialist',
    setting: 'PR agency or corporate PR',
    blurb: 'Pitches, spokespeople, and reputation risk.',
    family: 'Arts and Communication',
    themes: ['pitches', 'spokespeople', 'crises', 'coverage', 'measurement'],
  },
  {
    slug: 'video-editor',
    role: 'Video Editor',
    setting: 'Production house',
    blurb: 'Story, pace, and client notes.',
    family: 'Arts and Communication',
    themes: ['story', 'pace', 'color', 'audio', 'versions'],
  },
  {
    slug: 'photographer',
    role: 'Photographer',
    setting: 'Commercial photography',
    blurb: 'Light, direction, and delivery standards.',
    family: 'Arts and Communication',
    themes: ['lighting', 'direction', 'retouch', 'rights', 'delivery'],
  },
  {
    slug: 'animator',
    role: 'Animator',
    setting: 'Motion / animation studio',
    blurb: 'Timing, style frames, and pipeline handoffs.',
    family: 'Arts and Communication',
    themes: ['timing', 'style', 'rigging', 'pipeline', 'feedback'],
  },
  {
    slug: 'art-director',
    role: 'Art Director',
    setting: 'Creative agency',
    blurb: 'Concept, craft, and team direction.',
    family: 'Arts and Communication',
    themes: ['concept', 'craft', 'reviews', 'team', 'clients'],
  },
  {
    slug: 'technical-writer',
    role: 'Technical Writer',
    setting: 'Product documentation team',
    blurb: 'Clarity, accuracy, and versioned docs.',
    family: 'Arts and Communication',
    themes: ['clarity', 'API docs', 'versioning', 'examples', 'reviews'],
  },
  {
    slug: 'social-media-manager',
    role: 'Social Media Manager',
    setting: 'Brand social team',
    blurb: 'Calendar, community, and escalation judgment.',
    family: 'Arts and Communication',
    themes: ['calendar', 'community', 'analytics', 'escalation', 'brand'],
  },
  {
    slug: 'podcast-producer',
    role: 'Podcast Producer',
    setting: 'Audio / podcast studio',
    blurb: 'Booking, edits, and show consistency.',
    family: 'Arts and Communication',
    themes: ['booking', 'edits', 'show notes', 'distribution', 'guests'],
  },
  {
    slug: 'brand-strategist',
    role: 'Brand Strategist',
    setting: 'Brand strategy practice',
    blurb: 'Positioning, research, and narrative.',
    family: 'Arts and Communication',
    themes: ['positioning', 'research', 'narrative', 'workshops', 'guardrails'],
  },
  {
    slug: 'creative-director',
    role: 'Creative Director',
    setting: 'Creative leadership',
    blurb: 'Vision, quality bar, and client trust.',
    family: 'Arts and Communication',
    themes: ['vision', 'quality bar', 'pitches', 'talent', 'clients'],
  },
  {
    slug: 'motion-designer',
    role: 'Motion Designer',
    setting: 'Motion design team',
    blurb: 'Systems, timing, and brand motion language.',
    family: 'Arts and Communication',
    themes: ['systems', 'easing', 'brand', 'tooling', 'handoffs'],
  },
  {
    slug: 'editor',
    role: 'Editor',
    setting: 'Publishing / editorial team',
    blurb: 'Structure, voice, and fact discipline.',
    family: 'Arts and Communication',
    themes: ['structure', 'voice', 'facts', 'line edits', 'deadlines'],
  },
  {
    slug: 'illustrator',
    role: 'Illustrator',
    setting: 'Illustration / publishing',
    blurb: 'Style consistency and brief interpretation.',
    family: 'Arts and Communication',
    themes: ['style', 'briefs', 'revisions', 'composition', 'delivery'],
  },
  {
    slug: 'radio-producer',
    role: 'Radio Producer',
    setting: 'Broadcast / radio station',
    blurb: 'Segments, timing, and live problem-solving.',
    family: 'Arts and Communication',
    themes: ['segments', 'timing', 'guests', 'board ops', 'compliance'],
  },
  // Hospitality and Tourism
  {
    slug: 'hotel-operations-manager',
    role: 'Hotel Operations Manager',
    setting: 'Full-service hotel',
    blurb: 'Occupancy, service recovery, and team leadership.',
    family: 'Hospitality and Tourism',
    themes: ['occupancy', 'service recovery', 'staffing', 'P&L', 'standards'],
  },
  {
    slug: 'restaurant-manager',
    role: 'Restaurant Manager',
    setting: 'Full-service restaurant',
    blurb: 'Service, labor, food cost, and guest recovery.',
    family: 'Hospitality and Tourism',
    themes: ['labor', 'food cost', 'service', 'reservations', 'health codes'],
  },
  {
    slug: 'event-planner',
    role: 'Event Planner',
    setting: 'Events / catering company',
    blurb: 'Timelines, vendors, and day-of contingencies.',
    family: 'Hospitality and Tourism',
    themes: ['timelines', 'vendors', 'BEOs', 'contingencies', 'guests'],
  },
  {
    slug: 'concierge',
    role: 'Concierge',
    setting: 'Luxury hotel lobby',
    blurb: 'Local expertise, discretion, and impossible asks.',
    family: 'Hospitality and Tourism',
    themes: ['local knowledge', 'discretion', 'partners', 'VIPs', 'recovery'],
  },
  {
    slug: 'travel-advisor',
    role: 'Travel Advisor',
    setting: 'Travel agency / advisory',
    blurb: 'Itineraries, disruptions, and client preferences.',
    family: 'Hospitality and Tourism',
    themes: ['itineraries', 'air', 'hotels', 'disruption', 'preferences'],
  },
  {
    slug: 'executive-chef',
    role: 'Executive Chef',
    setting: 'Restaurant or hotel kitchen',
    blurb: 'Menu, food cost, and kitchen leadership.',
    family: 'Hospitality and Tourism',
    themes: ['menu', 'food cost', 'brigade', 'quality', 'ordering'],
  },
  {
    slug: 'front-desk-manager',
    role: 'Front Desk Manager',
    setting: 'Hotel front office',
    blurb: 'Check-in flow, upsell, and complaint handling.',
    family: 'Hospitality and Tourism',
    themes: ['check-in', 'PMS', 'upsell', 'complaints', 'night audit'],
  },
  {
    slug: 'housekeeping-manager',
    role: 'Housekeeping Manager',
    setting: 'Hotel housekeeping',
    blurb: 'Room turns, quality, and staffing curves.',
    family: 'Hospitality and Tourism',
    themes: ['room turns', 'inspectors', 'staffing', 'linen', 'lost & found'],
  },
  {
    slug: 'tourism-director',
    role: 'Tourism Director',
    setting: 'DMO / tourism board',
    blurb: 'Destination marketing and partner alignment.',
    family: 'Hospitality and Tourism',
    themes: ['destination', 'partners', 'events', 'metrics', 'seasonality'],
  },
  {
    slug: 'banquet-manager',
    role: 'Banquet Manager',
    setting: 'Hotel banquet operations',
    blurb: 'BEOs, setups, and service timing.',
    family: 'Hospitality and Tourism',
    themes: ['BEOs', 'setups', 'timing', 'staffing', 'AV'],
  },
  {
    slug: 'spa-manager',
    role: 'Spa Manager',
    setting: 'Hotel spa / wellness',
    blurb: 'Bookings, therapists, and retail attach.',
    family: 'Hospitality and Tourism',
    themes: ['bookings', 'therapists', 'retail', 'sanitation', 'membership'],
  },
  {
    slug: 'cruise-director',
    role: 'Cruise Director',
    setting: 'Cruise ship entertainment',
    blurb: 'Programming, guest energy, and safety briefings.',
    family: 'Hospitality and Tourism',
    themes: ['programming', 'announcements', 'activities', 'safety', 'crew'],
  },
  {
    slug: 'catering-manager',
    role: 'Catering Manager',
    setting: 'Off-premise catering',
    blurb: 'Menus, logistics, and on-site execution.',
    family: 'Hospitality and Tourism',
    themes: ['menus', 'logistics', 'staffing', 'dietary', 'site'],
  },
  {
    slug: 'guest-services-manager',
    role: 'Guest Services Manager',
    setting: 'Resort guest services',
    blurb: 'Loyalty, recovery, and cross-department fixes.',
    family: 'Hospitality and Tourism',
    themes: ['loyalty', 'recovery', 'tickets', 'VIPs', 'surveys'],
  },
  {
    slug: 'food-beverage-director',
    role: 'Food & Beverage Director',
    setting: 'Hotel F&B leadership',
    blurb: 'Outlets, cost, and guest experience.',
    family: 'Hospitality and Tourism',
    themes: ['outlets', 'cost', 'menus', 'labor', 'reviews'],
  },
  {
    slug: 'reservations-manager',
    role: 'Reservations Manager',
    setting: 'Central reservations',
    blurb: 'Yield, channels, and group blocks.',
    family: 'Hospitality and Tourism',
    themes: ['yield', 'channels', 'groups', 'OTAs', 'forecast'],
  },
  {
    slug: 'hospitality-sales-manager',
    role: 'Hospitality Sales Manager',
    setting: 'Hotel sales office',
    blurb: 'Groups, RFPs, and conversion.',
    family: 'Hospitality and Tourism',
    themes: ['RFPs', 'groups', 'site tours', 'contracts', 'pipeline'],
  },
  {
    slug: 'resort-manager',
    role: 'Resort Manager',
    setting: 'Destination resort',
    blurb: 'Multi-outlet ops and seasonal demand.',
    family: 'Hospitality and Tourism',
    themes: ['seasonality', 'amenities', 'staffing', 'guest journey', 'P&L'],
  },
  {
    slug: 'sommelier',
    role: 'Sommelier',
    setting: 'Fine dining restaurant',
    blurb: 'Pairings, cellar, and guest education.',
    family: 'Hospitality and Tourism',
    themes: ['pairings', 'cellar', 'service', 'cost', 'education'],
  },
  {
    slug: 'bartender',
    role: 'Bartender',
    setting: 'High-volume bar',
    blurb: 'Speed, craft, and responsible service.',
    family: 'Hospitality and Tourism',
    themes: ['speed', 'recipes', 'POS', 'responsible service', 'upsell'],
  },
  // Agriculture and Natural Resources
  {
    slug: 'agronomist',
    role: 'Agronomist',
    setting: 'Crop consulting / ag retailer',
    blurb: 'Soil, pests, and yield recommendations.',
    family: 'Agriculture and Natural Resources',
    themes: ['soil', 'pests', 'yield', 'trials', 'recommendations'],
  },
  {
    slug: 'environmental-specialist',
    role: 'Environmental Specialist',
    setting: 'Environmental services firm',
    blurb: 'Sampling, permits, and remediation support.',
    family: 'Agriculture and Natural Resources',
    themes: ['sampling', 'permits', 'remediation', 'reporting', 'compliance'],
  },
  {
    slug: 'farm-manager',
    role: 'Farm Manager',
    setting: 'Commercial farm operation',
    blurb: 'Production plans, labor, and weather risk.',
    family: 'Agriculture and Natural Resources',
    themes: ['planting', 'labor', 'equipment', 'weather', 'markets'],
  },
  {
    slug: 'forestry-technician',
    role: 'Forestry Technician',
    setting: 'Forest service / timber',
    blurb: 'Inventory, silviculture, and fire awareness.',
    family: 'Agriculture and Natural Resources',
    themes: ['inventory', 'silviculture', 'GIS', 'fire', 'safety'],
  },
  {
    slug: 'soil-scientist',
    role: 'Soil Scientist',
    setting: 'Soil / conservation consulting',
    blurb: 'Surveys, classification, and land-use advice.',
    family: 'Agriculture and Natural Resources',
    themes: ['surveys', 'classification', 'nutrients', 'erosion', 'reports'],
  },
  {
    slug: 'wildlife-biologist',
    role: 'Wildlife Biologist',
    setting: 'Wildlife agency / NGO',
    blurb: 'Surveys, habitat, and stakeholder conflict.',
    family: 'Agriculture and Natural Resources',
    themes: ['surveys', 'habitat', 'telemetry', 'permits', 'stakeholders'],
  },
  {
    slug: 'veterinary-technician',
    role: 'Veterinary Technician',
    setting: 'Veterinary clinic / hospital',
    blurb: 'Triage, anesthesia support, and client education.',
    family: 'Agriculture and Natural Resources',
    themes: ['triage', 'anesthesia', 'labs', 'clients', 'restraint'],
  },
  {
    slug: 'horticulturist',
    role: 'Horticulturist',
    setting: 'Nursery / public gardens',
    blurb: 'Plant health, IPM, and display quality.',
    family: 'Agriculture and Natural Resources',
    themes: ['IPM', 'plant health', 'propagation', 'displays', 'irrigation'],
  },
  {
    slug: 'water-resource-specialist',
    role: 'Water Resource Specialist',
    setting: 'Water district / consulting',
    blurb: 'Allocation, quality, and drought planning.',
    family: 'Agriculture and Natural Resources',
    themes: ['allocation', 'quality', 'modeling', 'drought', 'stakeholders'],
  },
  {
    slug: 'conservation-scientist',
    role: 'Conservation Scientist',
    setting: 'Conservation agency',
    blurb: 'Land stewardship and incentive programs.',
    family: 'Agriculture and Natural Resources',
    themes: ['stewardship', 'incentives', 'monitoring', 'partnerships', 'reporting'],
  },
  {
    slug: 'aquaculture-technician',
    role: 'Aquaculture Technician',
    setting: 'Fish / shellfish farm',
    blurb: 'Water quality, feed, and biosecurity.',
    family: 'Agriculture and Natural Resources',
    themes: ['water quality', 'feed', 'biosecurity', 'harvest', 'records'],
  },
  {
    slug: 'pest-control-advisor',
    role: 'Pest Control Advisor',
    setting: 'Crop protection advising',
    blurb: 'Scouting, thresholds, and label compliance.',
    family: 'Agriculture and Natural Resources',
    themes: ['scouting', 'thresholds', 'labels', 'resistance', 'IPM'],
  },
  {
    slug: 'livestock-manager',
    role: 'Livestock Manager',
    setting: 'Ranch / dairy operation',
    blurb: 'Herd health, feed, and labor routines.',
    family: 'Agriculture and Natural Resources',
    themes: ['herd health', 'feed', 'breeding', 'labor', 'records'],
  },
  {
    slug: 'park-ranger',
    role: 'Park Ranger',
    setting: 'National / state park',
    blurb: 'Visitor safety, interpretation, and resource protection.',
    family: 'Agriculture and Natural Resources',
    themes: ['visitors', 'interpretation', 'enforcement', 'resources', 'emergencies'],
  },
  {
    slug: 'fishery-biologist',
    role: 'Fishery Biologist',
    setting: 'Fisheries agency',
    blurb: 'Stock assessment and habitat projects.',
    family: 'Agriculture and Natural Resources',
    themes: ['stock assessment', 'habitat', 'sampling', 'regulations', 'partners'],
  },
  {
    slug: 'greenhouse-manager',
    role: 'Greenhouse Manager',
    setting: 'Commercial greenhouse',
    blurb: 'Climate control, labor, and crop scheduling.',
    family: 'Agriculture and Natural Resources',
    themes: ['climate', 'IPM', 'scheduling', 'labor', 'quality'],
  },
  {
    slug: 'extension-agent',
    role: 'Agricultural Extension Agent',
    setting: 'Cooperative extension',
    blurb: 'Education, demos, and community trust.',
    family: 'Agriculture and Natural Resources',
    themes: ['demos', 'education', 'needs assessment', 'partners', 'evaluation'],
  },
  {
    slug: 'natural-resource-manager',
    role: 'Natural Resource Manager',
    setting: 'Land management agency',
    blurb: 'Multi-use planning and compliance.',
    family: 'Agriculture and Natural Resources',
    themes: ['planning', 'permits', 'monitoring', 'conflict', 'NEPA'],
  },
  {
    slug: 'food-scientist',
    role: 'Food Scientist',
    setting: 'Food R&D / QA',
    blurb: 'Formulation, shelf life, and food safety.',
    family: 'Agriculture and Natural Resources',
    themes: ['formulation', 'shelf life', 'HACCP', 'sensory', 'scale-up'],
  },
  {
    slug: 'irrigation-specialist',
    role: 'Irrigation Specialist',
    setting: 'Irrigation design / ag ops',
    blurb: 'Efficiency, scheduling, and system diagnosis.',
    family: 'Agriculture and Natural Resources',
    themes: ['scheduling', 'efficiency', 'pumps', 'sensors', 'repairs'],
  },
  // Law and Public Safety
  {
    slug: 'attorney',
    role: 'Attorney',
    setting: 'Law firm or in-house counsel',
    blurb: 'Issue spotting, writing, and client counseling.',
    family: 'Law and Public Safety',
    themes: ['issue spotting', 'writing', 'negotiation', 'discovery', 'ethics'],
  },
  {
    slug: 'police-officer',
    role: 'Police Officer',
    setting: 'Municipal police department',
    blurb: 'De-escalation, report quality, and procedural justice.',
    family: 'Law and Public Safety',
    themes: ['de-escalation', 'reports', 'use of force', 'community', 'investigations'],
  },
  {
    slug: 'paralegal',
    role: 'Paralegal',
    setting: 'Litigation or transactional practice',
    blurb: 'Organization, drafting support, and deadlines.',
    family: 'Law and Public Safety',
    themes: ['organization', 'drafting', 'deadlines', 'discovery', 'filing'],
  },
  {
    slug: 'firefighter',
    role: 'Firefighter',
    setting: 'Fire / rescue department',
    blurb: 'Scene size-up, teamwork, and after-action learning.',
    family: 'Law and Public Safety',
    themes: ['size-up', 'hose lines', 'EMS', 'teamwork', 'fitness'],
  },
  {
    slug: 'corrections-officer',
    role: 'Corrections Officer',
    setting: 'Correctional facility',
    blurb: 'Safety, procedures, and conflict management.',
    family: 'Law and Public Safety',
    themes: ['safety', 'counts', 'searches', 'conflict', 'reports'],
  },
  {
    slug: 'probation-officer',
    role: 'Probation Officer',
    setting: 'Community corrections',
    blurb: 'Case plans, accountability, and risk tools.',
    family: 'Law and Public Safety',
    themes: ['case plans', 'risk tools', 'home visits', 'violations', 'resources'],
  },
  {
    slug: 'detective',
    role: 'Detective',
    setting: 'Investigations unit',
    blurb: 'Evidence, interviews, and case building.',
    family: 'Law and Public Safety',
    themes: ['evidence', 'interviews', 'warrants', 'case files', 'court'],
  },
  {
    slug: 'legal-secretary',
    role: 'Legal Secretary',
    setting: 'Law office support',
    blurb: 'Calendaring, filings, and attorney support.',
    family: 'Law and Public Safety',
    themes: ['calendaring', 'filings', 'correspondence', 'billing', 'confidentiality'],
  },
  {
    slug: 'court-clerk',
    role: 'Court Clerk',
    setting: 'Courthouse clerk\'s office',
    blurb: 'Dockets, filings, and public-facing accuracy.',
    family: 'Law and Public Safety',
    themes: ['dockets', 'filings', 'records', 'public', 'procedures'],
  },
  {
    slug: 'emergency-dispatcher',
    role: 'Emergency Dispatcher',
    setting: '911 / public safety communications',
    blurb: 'Triage, protocols, and multi-unit coordination.',
    family: 'Law and Public Safety',
    themes: ['protocols', 'triage', 'CAD', 'calm voice', 'updates'],
  },
  {
    slug: 'security-manager',
    role: 'Security Manager',
    setting: 'Corporate / campus security',
    blurb: 'Threat assessment, vendors, and incident response.',
    family: 'Law and Public Safety',
    themes: ['threats', 'access control', 'vendors', 'incidents', 'training'],
  },
  {
    slug: 'private-investigator',
    role: 'Private Investigator',
    setting: 'Investigations firm',
    blurb: 'Surveillance ethics, reports, and chain of custody.',
    family: 'Law and Public Safety',
    themes: ['surveillance', 'records', 'interviews', 'reports', 'ethics'],
  },
  {
    slug: 'forensic-technician',
    role: 'Forensic Technician',
    setting: 'Crime lab / CSI unit',
    blurb: 'Collection, packaging, and contamination control.',
    family: 'Law and Public Safety',
    themes: ['collection', 'packaging', 'photography', 'chain of custody', 'lab'],
  },
  {
    slug: 'customs-officer',
    role: 'Customs Officer',
    setting: 'Border / customs agency',
    blurb: 'Inspections, law application, and traveler communication.',
    family: 'Law and Public Safety',
    themes: ['inspections', 'declarations', 'interdiction', 'systems', 'respect'],
  },
  {
    slug: 'prosecutor',
    role: 'Prosecutor',
    setting: 'District attorney\'s office',
    blurb: 'Charging judgment, discovery, and courtroom presence.',
    family: 'Law and Public Safety',
    themes: ['charging', 'discovery', 'victims', 'trials', 'ethics'],
  },
  {
    slug: 'public-defender',
    role: 'Public Defender',
    setting: 'Public defense office',
    blurb: 'Client trust, investigation, and advocacy under load.',
    family: 'Law and Public Safety',
    themes: ['clients', 'investigation', 'motions', 'plea counsel', 'caseload'],
  },
  {
    slug: 'victim-advocate',
    role: 'Victim Advocate',
    setting: 'Victim services program',
    blurb: 'Trauma-informed support and system navigation.',
    family: 'Law and Public Safety',
    themes: ['trauma-informed', 'safety planning', 'courts', 'resources', 'boundaries'],
  },
  {
    slug: 'bailiff',
    role: 'Court Bailiff',
    setting: 'Courthouse security',
    blurb: 'Courtroom order, prisoner movement, and discretion.',
    family: 'Law and Public Safety',
    themes: ['order', 'movement', 'screening', 'emergencies', 'decorum'],
  },
  {
    slug: 'fire-inspector',
    role: 'Fire Inspector',
    setting: 'Fire prevention bureau',
    blurb: 'Code inspections and cooperative compliance.',
    family: 'Law and Public Safety',
    themes: ['code', 'inspections', 'education', 'hazards', 'reports'],
  },
  {
    slug: 'crime-analyst',
    role: 'Crime Analyst',
    setting: 'Police crime analysis unit',
    blurb: 'Patterns, maps, and actionable briefs.',
    family: 'Law and Public Safety',
    themes: ['patterns', 'GIS', 'briefs', 'data quality', 'partners'],
  },
  // Science and Research
  {
    slug: 'research-scientist',
    role: 'Research Scientist',
    setting: 'Academic or industry lab',
    blurb: 'Hypothesis rigor, methods, and publication standards.',
    family: 'Science and Research',
    themes: ['hypotheses', 'methods', 'stats', 'publication', 'reproducibility'],
  },
  {
    slug: 'clinical-lab-scientist',
    role: 'Clinical Lab Scientist',
    setting: 'Hospital clinical laboratory',
    blurb: 'QC, critical values, and assay troubleshooting.',
    family: 'Science and Research',
    themes: ['QC', 'critical values', 'assays', 'LIS', 'troubleshooting'],
  },
  {
    slug: 'biostatistician',
    role: 'Biostatistician',
    setting: 'Clinical / public health stats',
    blurb: 'Study design, analysis plans, and clear reporting.',
    family: 'Science and Research',
    themes: ['design', 'SAP', 'models', 'multiplicity', 'reporting'],
  },
  {
    slug: 'chemist',
    role: 'Chemist',
    setting: 'Analytical / R&D chemistry lab',
    blurb: 'Methods, safety, and data integrity.',
    family: 'Science and Research',
    themes: ['methods', 'HPLC', 'safety', 'ELN', 'impurities'],
  },
  {
    slug: 'physicist',
    role: 'Physicist',
    setting: 'Research lab or applied physics',
    blurb: 'Models, experiments, and uncertainty.',
    family: 'Science and Research',
    themes: ['models', 'experiments', 'uncertainty', 'instrumentation', 'analysis'],
  },
  {
    slug: 'microbiologist',
    role: 'Microbiologist',
    setting: 'Microbiology lab',
    blurb: 'Culture, ID, and contamination control.',
    family: 'Science and Research',
    themes: ['culture', 'ID', 'aseptic', 'antimicrobials', 'biosafety'],
  },
  {
    slug: 'epidemiologist',
    role: 'Epidemiologist',
    setting: 'Public health department',
    blurb: 'Surveillance, outbreaks, and study design.',
    family: 'Science and Research',
    themes: ['surveillance', 'outbreaks', 'study design', 'confounding', 'comms'],
  },
  {
    slug: 'geneticist',
    role: 'Geneticist',
    setting: 'Genetics lab / clinic support',
    blurb: 'Variants, counseling boundaries, and data quality.',
    family: 'Science and Research',
    themes: ['variants', 'NGS', 'QC', 'interpretation', 'ethics'],
  },
  {
    slug: 'research-associate',
    role: 'Research Associate',
    setting: 'Biotech / academic lab',
    blurb: 'Protocols, notebooks, and assay reliability.',
    family: 'Science and Research',
    themes: ['protocols', 'notebooks', 'assays', 'inventory', 'team'],
  },
  {
    slug: 'lab-manager',
    role: 'Lab Manager',
    setting: 'Research laboratory operations',
    blurb: 'Safety, budgets, and equipment uptime.',
    family: 'Science and Research',
    themes: ['safety', 'budgets', 'equipment', 'training', 'procurement'],
  },
  {
    slug: 'clinical-research-coordinator',
    role: 'Clinical Research Coordinator',
    setting: 'Clinical trials site',
    blurb: 'Protocol fidelity, consent, and source docs.',
    family: 'Science and Research',
    themes: ['protocol', 'consent', 'source docs', 'visits', 'adverse events'],
  },
  {
    slug: 'biomedical-researcher',
    role: 'Biomedical Researcher',
    setting: 'Translational research lab',
    blurb: 'Models, translation, and collaboration.',
    family: 'Science and Research',
    themes: ['models', 'translation', 'grants', 'collaboration', 'IRB'],
  },
  {
    slug: 'geologist',
    role: 'Geologist',
    setting: 'Geoscience consulting / energy',
    blurb: 'Field mapping, logging, and hazard judgment.',
    family: 'Science and Research',
    themes: ['mapping', 'logging', 'hazards', 'samples', 'reports'],
  },
  {
    slug: 'marine-biologist',
    role: 'Marine Biologist',
    setting: 'Marine research program',
    blurb: 'Field campaigns, permits, and data pipelines.',
    family: 'Science and Research',
    themes: ['field', 'permits', 'diving', 'datasets', 'conservation'],
  },
  {
    slug: 'toxicologist',
    role: 'Toxicologist',
    setting: 'Toxicology / safety science',
    blurb: 'Dose-response, risk characterization, and reports.',
    family: 'Science and Research',
    themes: ['dose-response', 'risk', 'studies', 'reg guidance', 'writeups'],
  },
  {
    slug: 'pharmacologist',
    role: 'Pharmacologist',
    setting: 'Drug discovery / pharma',
    blurb: 'PK/PD, assays, and decision gates.',
    family: 'Science and Research',
    themes: ['PK/PD', 'assays', 'targets', 'gates', 'safety'],
  },
  {
    slug: 'materials-scientist',
    role: 'Materials Scientist',
    setting: 'Materials R&D lab',
    blurb: 'Characterization, processing, and property tradeoffs.',
    family: 'Science and Research',
    themes: ['characterization', 'processing', 'properties', 'DOE', 'failure'],
  },
  {
    slug: 'astronomer',
    role: 'Astronomer',
    setting: 'Observatory / research institute',
    blurb: 'Proposals, data reduction, and collaboration.',
    family: 'Science and Research',
    themes: ['proposals', 'instruments', 'reduction', 'pipelines', 'papers'],
  },
  {
    slug: 'research-analyst',
    role: 'Research Analyst',
    setting: 'Think tank / applied research',
    blurb: 'Lit reviews, methods, and stakeholder briefs.',
    family: 'Science and Research',
    themes: ['lit review', 'methods', 'datasets', 'briefs', 'uncertainty'],
  },
  {
    slug: 'lab-technician',
    role: 'Laboratory Technician',
    setting: 'Analytical / QC lab',
    blurb: 'SOPs, sample throughput, and documentation.',
    family: 'Science and Research',
    themes: ['SOPs', 'throughput', 'calibration', 'docs', 'safety'],
  },
  // Manufacturing and Production
  {
    slug: 'production-supervisor',
    role: 'Production Supervisor',
    setting: 'Manufacturing plant floor',
    blurb: 'Throughput, quality, and people leadership.',
    family: 'Manufacturing and Production',
    themes: ['throughput', 'quality', 'staffing', 'safety', 'downtime'],
  },
  {
    slug: 'quality-engineer',
    role: 'Quality Engineer',
    setting: 'Manufacturing quality',
    blurb: 'Root cause, CAPA, and customer escapes.',
    family: 'Manufacturing and Production',
    themes: ['CAPA', 'root cause', 'SPC', 'audits', 'escapes'],
  },
  {
    slug: 'manufacturing-engineer',
    role: 'Manufacturing Engineer',
    setting: 'Process engineering team',
    blurb: 'Process capability, fixtures, and change control.',
    family: 'Manufacturing and Production',
    themes: ['capability', 'fixtures', 'PFMEA', 'change control', 'yield'],
  },
  {
    slug: 'cnc-machinist',
    role: 'CNC Machinist',
    setting: 'Precision machine shop',
    blurb: 'Programs, setups, and first-article quality.',
    family: 'Manufacturing and Production',
    themes: ['setups', 'tooling', 'tolerances', 'first article', 'inspection'],
  },
  {
    slug: 'process-engineer',
    role: 'Process Engineer',
    setting: 'Continuous process plant',
    blurb: 'Yield, bottlenecks, and control limits.',
    family: 'Manufacturing and Production',
    themes: ['yield', 'bottlenecks', 'controls', 'DOE', 'waste'],
  },
  {
    slug: 'lean-specialist',
    role: 'Lean Specialist',
    setting: 'CI / Lean office',
    blurb: 'Kaizen, waste walks, and sustainment.',
    family: 'Manufacturing and Production',
    themes: ['kaizen', 'waste', 'standard work', 'VSM', 'sustain'],
  },
  {
    slug: 'maintenance-technician',
    role: 'Maintenance Technician',
    setting: 'Plant maintenance',
    blurb: 'PM, breakdowns, and spare strategy.',
    family: 'Manufacturing and Production',
    themes: ['PM', 'breakdowns', 'CMMS', 'spares', 'lockout'],
  },
  {
    slug: 'assembly-supervisor',
    role: 'Assembly Supervisor',
    setting: 'Assembly line leadership',
    blurb: 'Takt, quality, and training.',
    family: 'Manufacturing and Production',
    themes: ['takt', 'quality', 'training', 'andon', 'balance'],
  },
  {
    slug: 'packaging-engineer',
    role: 'Packaging Engineer',
    setting: 'Packaging development',
    blurb: 'Protection, cost, and line trials.',
    family: 'Manufacturing and Production',
    themes: ['protection', 'cost', 'line trials', 'specs', 'sustainability'],
  },
  {
    slug: 'plant-manager',
    role: 'Plant Manager',
    setting: 'Manufacturing plant leadership',
    blurb: 'Safety, cost, delivery, and culture.',
    family: 'Manufacturing and Production',
    themes: ['safety', 'cost', 'OTIF', 'culture', 'capex'],
  },
  {
    slug: 'inventory-control-specialist',
    role: 'Inventory Control Specialist',
    setting: 'Materials / stores',
    blurb: 'Accuracy, cycle counts, and shortage prevention.',
    family: 'Manufacturing and Production',
    themes: ['cycle counts', 'accuracy', 'minmax', 'shortages', 'ERP'],
  },
  {
    slug: 'reliability-engineer',
    role: 'Reliability Engineer',
    setting: 'Asset reliability team',
    blurb: 'Bad actors, RCM, and uptime.',
    family: 'Manufacturing and Production',
    themes: ['bad actors', 'RCM', 'MTBF', 'PdM', 'RCAs'],
  },
  {
    slug: 'tooling-engineer',
    role: 'Tooling Engineer',
    setting: 'Tooling / die engineering',
    blurb: 'Dies, life, and changeovers.',
    family: 'Manufacturing and Production',
    themes: ['dies', 'life', 'changeovers', 'GD&T', 'vendors'],
  },
  {
    slug: 'quality-inspector',
    role: 'Quality Inspector',
    setting: 'Incoming / in-process QC',
    blurb: 'Specs, gaging, and nonconformance.',
    family: 'Manufacturing and Production',
    themes: ['specs', 'gages', 'NCR', 'sampling', 'docs'],
  },
  {
    slug: 'production-planner',
    role: 'Production Planner',
    setting: 'Planning / scheduling desk',
    blurb: 'MRP, constraints, and promise dates.',
    family: 'Manufacturing and Production',
    themes: ['MRP', 'constraints', 'ATP', 'expedites', 'frozen zone'],
  },
  {
    slug: 'continuous-improvement-manager',
    role: 'Continuous Improvement Manager',
    setting: 'CI leadership',
    blurb: 'Pipeline of projects and coaching.',
    family: 'Manufacturing and Production',
    themes: ['A3', 'coaching', 'pipeline', 'savings', 'culture'],
  },
  {
    slug: 'automation-technician',
    role: 'Automation Technician',
    setting: 'Controls / automation team',
    blurb: 'PLCs, robots, and recovery from faults.',
    family: 'Manufacturing and Production',
    themes: ['PLC', 'robots', 'sensors', 'faults', 'safety'],
  },
  {
    slug: 'materials-planner',
    role: 'Materials Planner',
    setting: 'Supply planning',
    blurb: 'BOM, lead times, and shortage war rooms.',
    family: 'Manufacturing and Production',
    themes: ['BOM', 'lead times', 'safety stock', 'expedite', 'suppliers'],
  },
  {
    slug: 'warehouse-supervisor',
    role: 'Warehouse Supervisor',
    setting: 'Plant warehouse',
    blurb: 'Pick accuracy, safety, and labor.',
    family: 'Manufacturing and Production',
    themes: ['picks', 'slotting', 'safety', 'labor', 'cycle count'],
  },
  {
    slug: 'industrial-technician',
    role: 'Industrial Technician',
    setting: 'Industrial services',
    blurb: 'Installs, alignments, and service tickets.',
    family: 'Manufacturing and Production',
    themes: ['installs', 'alignment', 'tickets', 'parts', 'safety'],
  },
  // Transportation and Logistics
  {
    slug: 'supply-chain',
    role: 'Supply Chain / Procurement',
    setting: 'Supply chain organization',
    blurb: 'Sourcing, risk, and total cost.',
    family: 'Transportation and Logistics',
    themes: ['sourcing', 'risk', 'TCO', 'contracts', 'OTIF'],
  },
  {
    slug: 'logistics-coordinator',
    role: 'Logistics Coordinator',
    setting: '3PL / shipper logistics',
    blurb: 'Modes, exceptions, and customer updates.',
    family: 'Transportation and Logistics',
    themes: ['modes', 'exceptions', 'track/trace', 'docs', 'costs'],
  },
  {
    slug: 'truck-driver',
    role: 'Commercial Truck Driver',
    setting: 'Carrier / fleet operations',
    blurb: 'Hours, safety, and on-time deliveries.',
    family: 'Transportation and Logistics',
    themes: ['HOS', 'inspections', 'routes', 'customers', 'safety'],
  },
  {
    slug: 'warehouse-manager',
    role: 'Warehouse Manager',
    setting: 'Distribution center',
    blurb: 'Throughput, accuracy, and safety culture.',
    family: 'Transportation and Logistics',
    themes: ['throughput', 'accuracy', 'safety', 'labor', 'WMS'],
  },
  {
    slug: 'freight-broker',
    role: 'Freight Broker',
    setting: 'Freight brokerage',
    blurb: 'Capacity, pricing, and carrier vetting.',
    family: 'Transportation and Logistics',
    themes: ['capacity', 'pricing', 'carriers', 'claims', 'tracking'],
  },
  {
    slug: 'fleet-manager',
    role: 'Fleet Manager',
    setting: 'Corporate / carrier fleet',
    blurb: 'Utilization, maintenance, and compliance.',
    family: 'Transportation and Logistics',
    themes: ['utilization', 'maintenance', 'compliance', 'fuel', 'accidents'],
  },
  {
    slug: 'transportation-planner',
    role: 'Transportation Planner',
    setting: 'Shipper planning desk',
    blurb: 'Network, modes, and service levels.',
    family: 'Transportation and Logistics',
    themes: ['network', 'modes', 'SLAs', 'cost', 'seasonality'],
  },
  {
    slug: 'customs-broker',
    role: 'Customs Broker',
    setting: 'Customs brokerage',
    blurb: 'Entries, classification, and holds.',
    family: 'Transportation and Logistics',
    themes: ['entries', 'HTS', 'holds', 'bonds', 'compliance'],
  },
  {
    slug: 'dispatch-supervisor',
    role: 'Dispatch Supervisor',
    setting: 'Carrier dispatch',
    blurb: 'Load matching, ETA honesty, and driver care.',
    family: 'Transportation and Logistics',
    themes: ['loads', 'ETAs', 'drivers', 'exceptions', 'comms'],
  },
  {
    slug: 'shipping-coordinator',
    role: 'Shipping Coordinator',
    setting: 'Outbound shipping desk',
    blurb: 'Docs, carriers, and cutoffs.',
    family: 'Transportation and Logistics',
    themes: ['BOL', 'carriers', 'cutoffs', 'labels', 'claims'],
  },
  {
    slug: 'inventory-analyst',
    role: 'Inventory Analyst',
    setting: 'Inventory analytics',
    blurb: 'Turns, excess, and service tradeoffs.',
    family: 'Transportation and Logistics',
    themes: ['turns', 'excess', 'ABC', 'forecast', 'service'],
  },
  {
    slug: 'last-mile-manager',
    role: 'Last-Mile Manager',
    setting: 'Last-mile delivery ops',
    blurb: 'Density, failed attempts, and CX.',
    family: 'Transportation and Logistics',
    themes: ['density', 'attempts', 'CX', 'routing', 'returns'],
  },
  {
    slug: 'procurement-specialist',
    role: 'Procurement Specialist',
    setting: 'Strategic sourcing',
    blurb: 'RFPs, negotiations, and supplier performance.',
    family: 'Transportation and Logistics',
    themes: ['RFPs', 'negotiation', 'scorecards', 'risk', 'savings'],
  },
  {
    slug: 'import-export-specialist',
    role: 'Import/Export Specialist',
    setting: 'Global trade desk',
    blurb: 'Incoterms, docs, and duty management.',
    family: 'Transportation and Logistics',
    themes: ['Incoterms', 'docs', 'duty', 'partners', 'delays'],
  },
  {
    slug: 'airline-operations-manager',
    role: 'Airline Operations Manager',
    setting: 'Airline station ops',
    blurb: 'Irregs, turn times, and crew coordination.',
    family: 'Transportation and Logistics',
    themes: ['irregs', 'turns', 'crew', 'customers', 'safety'],
  },
  {
    slug: 'port-operations-supervisor',
    role: 'Port Operations Supervisor',
    setting: 'Port / terminal ops',
    blurb: 'Berths, yard flow, and dwell.',
    family: 'Transportation and Logistics',
    themes: ['berths', 'yard', 'dwell', 'labor', 'safety'],
  },
  {
    slug: 'route-planner',
    role: 'Route Planner',
    setting: 'Route optimization team',
    blurb: 'Constraints, windows, and cost.',
    family: 'Transportation and Logistics',
    themes: ['windows', 'constraints', 'cost', 'tools', 'exceptions'],
  },
  {
    slug: 'cold-chain-specialist',
    role: 'Cold Chain Specialist',
    setting: 'Temperature-controlled logistics',
    blurb: 'Excursions, packaging, and monitoring.',
    family: 'Transportation and Logistics',
    themes: ['excursions', 'packaging', 'monitors', 'SOP', 'claims'],
  },
  {
    slug: 'air-traffic-specialist',
    role: 'Air Traffic Operations Specialist',
    setting: 'Aviation operations support',
    blurb: 'Flow, weather, and coordination discipline.',
    family: 'Transportation and Logistics',
    themes: ['flow', 'weather', 'coordination', 'procedures', 'safety'],
  },
  {
    slug: 'intermodal-coordinator',
    role: 'Intermodal Coordinator',
    setting: 'Intermodal logistics',
    blurb: 'Dray, rail, and chassis constraints.',
    family: 'Transportation and Logistics',
    themes: ['dray', 'rail', 'chassis', 'dwell', 'updates'],
  },
  // Sales and Marketing
  {
    slug: 'marketing',
    role: 'Marketing Manager',
    setting: 'Growth marketing team',
    blurb: 'Channels, experiments, and creative briefs.',
    family: 'Sales and Marketing',
    themes: ['channels', 'experiments', 'briefs', 'attribution', 'pipeline'],
  },
  {
    slug: 'customer-success',
    role: 'Customer Success Manager',
    setting: 'B2B customer success',
    blurb: 'Adoption, renewals, and escalation judgment.',
    family: 'Sales and Marketing',
    themes: ['adoption', 'renewals', 'QBRs', 'health scores', 'escalation'],
  },
  {
    slug: 'account-executive',
    role: 'Account Executive',
    setting: 'Enterprise sales team',
    blurb: 'Discovery, mutual plans, and closing without pressure theater.',
    family: 'Sales and Marketing',
    themes: ['discovery', 'MEDDIC', 'demos', 'negotiation', 'forecast'],
  },
  {
    slug: 'sales-manager',
    role: 'Sales Manager',
    setting: 'Sales leadership',
    blurb: 'Coaching, forecast accuracy, and hiring.',
    family: 'Sales and Marketing',
    themes: ['coaching', 'forecast', 'pipeline', 'hiring', 'compensation'],
  },
  {
    slug: 'business-development',
    role: 'Business Development',
    setting: 'Partnerships / BD team',
    blurb: 'Partnerships, pilots, and commercial structure.',
    family: 'Sales and Marketing',
    themes: ['partnerships', 'pilots', 'ICPs', 'term sheets', 'pipeline'],
  },
  {
    slug: 'digital-marketing-manager',
    role: 'Digital Marketing Manager',
    setting: 'Performance marketing',
    blurb: 'Paid channels, creative tests, and CAC discipline.',
    family: 'Sales and Marketing',
    themes: ['paid', 'CAC', 'creative tests', 'landing pages', 'budget'],
  },
  {
    slug: 'seo-specialist',
    role: 'SEO Specialist',
    setting: 'Organic growth team',
    blurb: 'Technical SEO, content, and measurement.',
    family: 'Sales and Marketing',
    themes: ['technical SEO', 'content', 'keywords', 'links', 'reporting'],
  },
  {
    slug: 'brand-manager',
    role: 'Brand Manager',
    setting: 'CPG / brand marketing',
    blurb: 'Positioning, campaigns, and retailer execution.',
    family: 'Sales and Marketing',
    themes: ['positioning', 'campaigns', 'assortment', 'trade', 'NPD'],
  },
  {
    slug: 'market-research-analyst',
    role: 'Market Research Analyst',
    setting: 'Insights team',
    blurb: 'Surveys, synthesis, and decision-ready findings.',
    family: 'Sales and Marketing',
    themes: ['surveys', 'qual', 'segmentation', 'synthesis', 'decks'],
  },
  {
    slug: 'content-marketing-manager',
    role: 'Content Marketing Manager',
    setting: 'Content marketing',
    blurb: 'Editorial calendar and demand contribution.',
    family: 'Sales and Marketing',
    themes: ['calendar', 'funnels', 'distribution', 'voice', 'measurement'],
  },
  {
    slug: 'sales-development-representative',
    role: 'Sales Development Representative',
    setting: 'Outbound / inbound SDR',
    blurb: 'Prospecting, qualification, and handoffs.',
    family: 'Sales and Marketing',
    themes: ['prospecting', 'qualification', 'sequences', 'handoffs', 'CRM'],
  },
  {
    slug: 'retail-sales-associate',
    role: 'Retail Sales Associate',
    setting: 'Retail store floor',
    blurb: 'Service, product knowledge, and conversion.',
    family: 'Sales and Marketing',
    themes: ['service', 'product knowledge', 'conversion', 'OPS', 'recovery'],
  },
  {
    slug: 'inside-sales-representative',
    role: 'Inside Sales Representative',
    setting: 'Inside sales team',
    blurb: 'Phone/video selling and pipeline hygiene.',
    family: 'Sales and Marketing',
    themes: ['discovery', 'demos', 'objections', 'CRM', 'follow-up'],
  },
  {
    slug: 'channel-partner-manager',
    role: 'Channel Partner Manager',
    setting: 'Partner channel org',
    blurb: 'Enablement, conflict, and joint pipeline.',
    family: 'Sales and Marketing',
    themes: ['enablement', 'conflict', 'MDF', 'pipeline', 'scorecards'],
  },
  {
    slug: 'demand-generation-manager',
    role: 'Demand Generation Manager',
    setting: 'Demand gen team',
    blurb: 'Programs, MQLs, and sales alignment.',
    family: 'Sales and Marketing',
    themes: ['programs', 'MQLs', 'nurture', 'events', 'alignment'],
  },
  {
    slug: 'product-marketing-manager',
    role: 'Product Marketing Manager',
    setting: 'Product marketing',
    blurb: 'Positioning, launches, and sales enablement.',
    family: 'Sales and Marketing',
    themes: ['positioning', 'launches', 'battlecards', 'personas', 'win/loss'],
  },
  {
    slug: 'email-marketing-specialist',
    role: 'Email Marketing Specialist',
    setting: 'Lifecycle marketing',
    blurb: 'Flows, deliverability, and tests.',
    family: 'Sales and Marketing',
    themes: ['flows', 'deliverability', 'tests', 'segmentation', 'compliance'],
  },
  {
    slug: 'growth-marketer',
    role: 'Growth Marketer',
    setting: 'Growth squad',
    blurb: 'Experiments, activation, and north-star metrics.',
    family: 'Sales and Marketing',
    themes: ['experiments', 'activation', 'retention', 'instrumentation', 'velocity'],
  },
  {
    slug: 'account-manager',
    role: 'Account Manager',
    setting: 'Post-sale account team',
    blurb: 'Expansion, relationships, and delivery coordination.',
    family: 'Sales and Marketing',
    themes: ['expansion', 'relationships', 'QBRs', 'delivery', 'risk'],
  },
  {
    slug: 'retail-store-manager',
    role: 'Retail Store Manager',
    setting: 'Retail store leadership',
    blurb: 'Sales, labor, and visual standards.',
    family: 'Sales and Marketing',
    themes: ['sales', 'labor', 'visuals', 'shrink', 'coaching'],
  },
  // Government and Public Admin
  {
    slug: 'policy-analyst',
    role: 'Policy Analyst',
    setting: 'Government policy shop',
    blurb: 'Evidence, options memos, and stakeholder maps.',
    family: 'Government and Public Admin',
    themes: ['evidence', 'options memos', 'stakeholders', 'budget', 'implementation'],
  },
  {
    slug: 'city-administrator',
    role: 'City Administrator',
    setting: 'City manager\'s office',
    blurb: 'Council relations, budget, and service delivery.',
    family: 'Government and Public Admin',
    themes: ['council', 'budget', 'services', 'crisis', 'staff'],
  },
  {
    slug: 'legislative-aide',
    role: 'Legislative Aide',
    setting: 'Legislator\'s office',
    blurb: 'Constituent work, briefings, and bill tracking.',
    family: 'Government and Public Admin',
    themes: ['constituents', 'briefings', 'bills', 'scheduling', 'comms'],
  },
  {
    slug: 'public-budget-analyst',
    role: 'Public Budget Analyst',
    setting: 'Budget office',
    blurb: 'Base budgets, justifications, and tradeoffs.',
    family: 'Government and Public Admin',
    themes: ['base budgets', 'justifications', 'performance', 'cuts', 'forecasts'],
  },
  {
    slug: 'grant-writer',
    role: 'Grant Writer',
    setting: 'Public / nonprofit grants',
    blurb: 'Narratives, budgets, and compliance readiness.',
    family: 'Government and Public Admin',
    themes: ['narratives', 'budgets', 'logic models', 'compliance', 'deadlines'],
  },
  {
    slug: 'election-administrator',
    role: 'Election Administrator',
    setting: 'Elections office',
    blurb: 'Procedures, poll workers, and public trust.',
    family: 'Government and Public Admin',
    themes: ['procedures', 'poll workers', 'ballots', 'security', 'public'],
  },
  {
    slug: 'emergency-management-coordinator',
    role: 'Emergency Management Coordinator',
    setting: 'Emergency management agency',
    blurb: 'Plans, EOCs, and after-action learning.',
    family: 'Government and Public Admin',
    themes: ['plans', 'EOC', 'ICS', 'partners', 'AARs'],
  },
  {
    slug: 'public-affairs-officer',
    role: 'Public Affairs Officer',
    setting: 'Agency communications',
    blurb: 'Clear public updates and media discipline.',
    family: 'Government and Public Admin',
    themes: ['updates', 'media', 'message maps', 'rumors', 'accessibility'],
  },
  {
    slug: 'zoning-inspector',
    role: 'Zoning Inspector',
    setting: 'Planning / code enforcement',
    blurb: 'Code application and respectful enforcement.',
    family: 'Government and Public Admin',
    themes: ['zoning', 'inspections', 'notices', 'appeals', 'docs'],
  },
  {
    slug: 'municipal-clerk',
    role: 'Municipal Clerk',
    setting: 'City clerk\'s office',
    blurb: 'Records, agendas, and public meeting law.',
    family: 'Government and Public Admin',
    themes: ['agendas', 'minutes', 'records', 'FOIA', 'elections'],
  },
  {
    slug: 'foreign-service-officer',
    role: 'Foreign Service Officer',
    setting: 'Diplomatic service',
    blurb: 'Reporting, representation, and crisis judgment.',
    family: 'Government and Public Admin',
    themes: ['reporting', 'representation', 'contacts', 'crisis', 'policy'],
  },
  {
    slug: 'intelligence-analyst',
    role: 'Intelligence Analyst',
    setting: 'Intelligence / analytic unit',
    blurb: 'Sources, analytic rigor, and briefings.',
    family: 'Government and Public Admin',
    themes: ['sources', 'rigor', 'briefs', 'collection', 'bias'],
  },
  {
    slug: 'regulatory-affairs-specialist',
    role: 'Regulatory Affairs Specialist',
    setting: 'Agency or regulated industry',
    blurb: 'Filings, comments, and interpretation.',
    family: 'Government and Public Admin',
    themes: ['filings', 'comments', 'guidance', 'timelines', 'risk'],
  },
  {
    slug: 'community-development-director',
    role: 'Community Development Director',
    setting: 'City community development',
    blurb: 'Housing, grants, and neighborhood partnerships.',
    family: 'Government and Public Admin',
    themes: ['housing', 'grants', 'partners', 'zoning', 'equity'],
  },
  {
    slug: 'public-works-director',
    role: 'Public Works Director',
    setting: 'Public works department',
    blurb: 'Infrastructure, storms, and contractor oversight.',
    family: 'Government and Public Admin',
    themes: ['infrastructure', 'storms', 'contractors', 'budget', 'safety'],
  },
  {
    slug: 'housing-specialist',
    role: 'Housing Specialist',
    setting: 'Housing authority',
    blurb: 'Eligibility, waitlists, and landlord coordination.',
    family: 'Government and Public Admin',
    themes: ['eligibility', 'waitlists', 'inspections', 'landlords', 'casework'],
  },
  {
    slug: 'tax-assessor',
    role: 'Tax Assessor',
    setting: 'Assessment office',
    blurb: 'Valuation, appeals, and equity.',
    family: 'Government and Public Admin',
    themes: ['valuation', 'appeals', 'equity', 'data', 'public'],
  },
  {
    slug: 'census-analyst',
    role: 'Census / Demographic Analyst',
    setting: 'Statistical agency team',
    blurb: 'Survey methods and population estimates.',
    family: 'Government and Public Admin',
    themes: ['surveys', 'estimates', 'weighting', 'disclosure', 'maps'],
  },
  {
    slug: 'program-evaluator',
    role: 'Program Evaluator',
    setting: 'Performance / evaluation office',
    blurb: 'Logic models, metrics, and honest findings.',
    family: 'Government and Public Admin',
    themes: ['logic models', 'metrics', 'methods', 'findings', 'use'],
  },
  {
    slug: 'ombuds',
    role: 'Ombuds / Constituent Services',
    setting: 'Ombuds office',
    blurb: 'Neutral inquiry and system improvement.',
    family: 'Government and Public Admin',
    themes: ['intake', 'neutrality', 'escalation', 'patterns', 'reports'],
  },
  // Human Services
  {
    slug: 'social-worker',
    role: 'Social Worker',
    setting: 'Clinical / case management setting',
    blurb: 'Assessment, safety, and ethical boundaries.',
    family: 'Human Services',
    themes: ['assessment', 'safety', 'ethics', 'resources', 'documentation'],
  },
  {
    slug: 'people-ops',
    role: 'People Operations',
    setting: 'People ops / HR ops team',
    blurb: 'Employee lifecycle, policy, and sensitive cases.',
    family: 'Human Services',
    themes: ['lifecycle', 'policy', 'cases', 'systems', 'equity'],
  },
  {
    slug: 'hr-business-partner',
    role: 'HR Business Partner',
    setting: 'HRBP supporting leaders',
    blurb: 'Coaching managers and org design judgment.',
    family: 'Human Services',
    themes: ['coaching', 'ER', 'org design', 'performance', 'talent'],
  },
  {
    slug: 'career-counselor',
    role: 'Career Counselor',
    setting: 'Career services center',
    blurb: 'Assessment, coaching, and realistic pathways.',
    family: 'Human Services',
    themes: ['assessment', 'coaching', 'resumes', 'networks', 'labor market'],
  },
  {
    slug: 'case-manager',
    role: 'Case Manager',
    setting: 'Human services agency',
    blurb: 'Plans, coordination, and barrier removal.',
    family: 'Human Services',
    themes: ['plans', 'coordination', 'barriers', 'benefits', 'follow-up'],
  },
  {
    slug: 'mental-health-counselor',
    role: 'Mental Health Counselor',
    setting: 'Outpatient counseling clinic',
    blurb: 'Alliance, treatment plans, and crisis protocols.',
    family: 'Human Services',
    themes: ['alliance', 'treatment plans', 'crisis', 'modalities', 'notes'],
  },
  {
    slug: 'substance-abuse-counselor',
    role: 'Substance Abuse Counselor',
    setting: 'SUD treatment program',
    blurb: 'Motivation, relapse planning, and group work.',
    family: 'Human Services',
    themes: ['motivation', 'relapse', 'groups', 'screening', 'referrals'],
  },
  {
    slug: 'child-welfare-worker',
    role: 'Child Welfare Worker',
    setting: 'Child protective services',
    blurb: 'Safety assessments and family engagement.',
    family: 'Human Services',
    themes: ['safety', 'engagement', 'court', 'placements', 'docs'],
  },
  {
    slug: 'community-outreach-coordinator',
    role: 'Community Outreach Coordinator',
    setting: 'Nonprofit / community org',
    blurb: 'Trust, events, and partnership building.',
    family: 'Human Services',
    themes: ['trust', 'events', 'partners', 'messaging', 'feedback'],
  },
  {
    slug: 'nonprofit-program-manager',
    role: 'Nonprofit Program Manager',
    setting: 'Nonprofit program team',
    blurb: 'Outcomes, staffing, and funder reporting.',
    family: 'Human Services',
    themes: ['outcomes', 'staffing', 'funders', 'budget', 'quality'],
  },
  {
    slug: 'rehabilitation-counselor',
    role: 'Rehabilitation Counselor',
    setting: 'Vocational rehab',
    blurb: 'Disability employment and accommodation plans.',
    family: 'Human Services',
    themes: ['assessment', 'placements', 'accommodations', 'employers', 'plans'],
  },
  {
    slug: 'family-therapist',
    role: 'Marriage & Family Therapist',
    setting: 'Family therapy practice',
    blurb: 'Systems work, alliances, and ethics.',
    family: 'Human Services',
    themes: ['systems', 'alliances', 'ethics', 'sessions', 'safety'],
  },
  {
    slug: 'victim-services-coordinator',
    role: 'Victim Services Coordinator',
    setting: 'Victim services nonprofit',
    blurb: 'Trauma-informed navigation and advocacy.',
    family: 'Human Services',
    themes: ['trauma-informed', 'advocacy', 'safety', 'partners', 'boundaries'],
  },
  {
    slug: 'residential-counselor',
    role: 'Residential Counselor',
    setting: 'Group home / residential program',
    blurb: 'Milieu, de-escalation, and documentation.',
    family: 'Human Services',
    themes: ['milieu', 'de-escalation', 'meds support', 'shifts', 'docs'],
  },
  {
    slug: 'benefits-specialist',
    role: 'Benefits Specialist',
    setting: 'HR benefits team',
    blurb: 'Plans, life events, and clear counseling.',
    family: 'Human Services',
    themes: ['plans', 'life events', 'eligibility', 'vendors', 'comms'],
  },
  {
    slug: 'talent-acquisition-specialist',
    role: 'Talent Acquisition Specialist',
    setting: 'Recruiting team',
    blurb: 'Sourcing, process design, and candidate experience.',
    family: 'Human Services',
    themes: ['sourcing', 'pipelines', 'interviews', 'offers', 'experience'],
  },
  {
    slug: 'employee-relations-specialist',
    role: 'Employee Relations Specialist',
    setting: 'ER / investigations',
    blurb: 'Fair process, documentation, and risk judgment.',
    family: 'Human Services',
    themes: ['investigations', 'fairness', 'docs', 'policy', 'remedies'],
  },
  {
    slug: 'diversity-inclusion-specialist',
    role: 'Diversity & Inclusion Specialist',
    setting: 'DEI / belonging team',
    blurb: 'Programs, data, and credible facilitation.',
    family: 'Human Services',
    themes: ['programs', 'data', 'facilitation', 'ERGs', 'metrics'],
  },
  {
    slug: 'volunteer-coordinator',
    role: 'Volunteer Coordinator',
    setting: 'Volunteer programs',
    blurb: 'Recruiting, training, and retention of volunteers.',
    family: 'Human Services',
    themes: ['recruiting', 'training', 'scheduling', 'recognition', 'risk'],
  },
  {
    slug: 'elder-care-coordinator',
    role: 'Elder Care Coordinator',
    setting: 'Aging services',
    blurb: 'Care plans, caregivers, and resource navigation.',
    family: 'Human Services',
    themes: ['care plans', 'caregivers', 'benefits', 'safety', 'providers'],
  },
];
